export const THRESHOLDS = {
  title: { minLength: 30, maxLength: 60 },
  description: { minLength: 50, maxLength: 160 },
  ogImage: { minSizeBytes: 1024 },
  lcp: { poor: 4000, needsImprovement: 2500 },
  cls: { poor: 0.25, needsImprovement: 0.1 },
  inp: { poor: 200, needsImprovement: 100 },
  consoleErrors: { some: 1, critical: 5 },
  design: { maxFontFamilies: 3, maxButtonRadiusSpread: 4 },
  slowReplay: { blankScreenMs: 5000, ctaTimeoutMs: 8000 },
  postClick: { blankDestinationMs: 3000, stuckLoadingMs: 2000 },
  formFeedback: { slowMs: 1000 },
  flowTimeoutMs: 30_000,
  pageSpeedScore: { poor: 50, needsImprovement: 80 },
  mobilePerfScore: { poor: 40, needsImprovement: 60 },
  tapTargetMinPx: 48,
  criticalPathConcurrency: 3,
  maxUrlsPerPattern: 3,
  severityPenalties: {
    CRITICAL: 25,
    IMPORTANT: 15,
    POLISH: 5,
  } as const,
  gradeThresholds: {
    A: 90,
    B: 75,
    C: 60,
    D: 40,
  } as const,
} as const
