import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { CareHomepage } from '../CareHomepage'
import { CARE_HOME as C, INTEGRATIONS_PAGE } from '@/lib/marketing/copy'
import { HOMEPAGE_SAMPLE as S, SAMPLE_FLAGS } from '@/lib/marketing/copy/care-homepage'
import { watchableOutcomeKinds } from '@/lib/sites/outcome-kinds'
import { SITE_CARD_AREAS } from '@/lib/sites/card-areas'
import { Toaster, toast } from 'sonner'

vi.mock('@/components/audit/AuditInput', () => ({ AuditInput: () => <div data-testid="url-entry" /> }))
vi.mock('next/image', () => ({ default: ({ alt, src }: { alt: string; src: string }) => <span role="img" aria-label={alt} data-src={src} /> }))
afterEach(() => { toast.dismiss(); cleanup(); vi.restoreAllMocks() })

function openCategory(name: string) {
  fireEvent.click(screen.getByRole('button', { name: `Open ${name}` }))
  return screen.getByRole('dialog')
}

describe('comprehensive homepage experience', () => {
  it('edits custom sample schedules from the monitoring summary and preserves the selection', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    fireEvent.click(within(board).getByRole('button', { name: 'Monitoring Daily. Next check in 23 hours and 45 minutes' }))
    const dialog = screen.getByRole('dialog')
    expect(within(dialog).getByText('This is a sample schedule. Changes only affect this preview.')).toBeVisible()
    fireEvent.change(within(dialog).getByRole('combobox', { name: 'Check frequency' }), { target: { value: 'custom' } })
    fireEvent.change(within(dialog).getByRole('spinbutton', { name: 'Every' }), { target: { value: '3' } })
    fireEvent.change(within(dialog).getByRole('combobox', { name: 'Time unit' }), { target: { value: 'hours' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Update sample schedule' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    const summary = within(board).getByRole('button', { name: 'Monitoring Every 3 hours. Next check in 2 hours and 45 minutes' })
    expect(summary).toBeVisible()
    fireEvent.click(summary)
    expect(screen.getByRole('spinbutton', { name: 'Every' })).toHaveValue(3)
    expect(screen.getByRole('combobox', { name: 'Time unit' })).toHaveValue('hours')
  })

  it('opens cart evidence and detected-page details from the overview', () => {
    render(<CareHomepage />)
    let dialog = openCategory('Conversion')
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for Add to cart' }))
    dialog = screen.getByRole('dialog')
    expect(within(dialog).getByRole('heading', { name: SAMPLE_FLAGS.checkout.title })).toBeVisible()
    expect(within(dialog).getByText(SAMPLE_FLAGS.checkout.observed)).toBeVisible()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Close' }))
    fireEvent.click(screen.getByRole('button', { name: '12 Pages. 2 need attention' }))
    const pages = screen.getByRole('dialog')
    expect(within(pages).getByRole('heading', { name: 'Pages' })).toBeVisible()
    expect(within(pages).getByText('10 other pages')).toBeVisible()
    expect(screen.queryByRole('link', { name: /Add signup monitoring/ })).not.toBeInTheDocument()
  })
  it('keeps the brand, two URL entries and the sample-to-analysis path', () => {
    render(<CareHomepage />)
    expect(screen.getByRole('heading', { level: 1, name: /Finish what\s*your AI started/ })).toBeVisible()
    expect(screen.getAllByTestId('url-entry')).toHaveLength(2)
    expect(screen.getByText(C.hero.eyebrow)).toBeVisible()
    expect(screen.getByText(C.hero.body)).toBeVisible()
    for (const benefit of C.hero.benefits) expect(screen.getByText(benefit.title)).toBeVisible()
    expect(screen.queryByRole('link', { name: S.exploreAction })).not.toBeInTheDocument()
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
    const board = screen.getByRole('region', { name: C.boardAria })
    for (const card of S.categories) expect(within(board).getByRole('button', { name: `Open ${card.name}` })).toBeVisible()
    expect(within(board).getAllByText('0 Flags')).toHaveLength(6)
    const summary = within(board).getByRole('group', { name: S.summaryLabel })
    expect(within(summary).getByText('3')).toBeVisible()
    expect(within(summary).getByText('Flags')).toBeVisible()
    expect(within(summary).getByText('Pages')).toBeVisible()
    expect(within(summary).getByText('2 need attention')).toBeVisible()
    expect(within(summary).getByText('Daily')).toBeVisible()
    expect(within(summary).getByText('Monitoring')).toBeVisible()
    expect(within(summary).getByText('Next in 23h 45m')).toBeVisible()
    expect(within(board).getByText('www.examplesites.com')).toBeVisible()
    expect(within(board).getByRole('region', { name: 'Detected technologies' })).toBeVisible()
    expect(within(board).getAllByText('15 minutes ago')).toHaveLength(9)
    expect(within(board).queryByText(/Last check/)).not.toBeInTheDocument()
    expect(within(board).getByTitle('3 Flags on this website')).toBeVisible()
    expect(within(board).getByRole('link', { name: 'Recheck website' })).toHaveAttribute('href', '#analyze')
    expect(within(board).queryByRole('button', { name: 'Flags', exact: true })).not.toBeInTheDocument()
    expect(within(board).queryByRole('link', { name: /Analyze .* again/ })).not.toBeInTheDocument()
    expect(within(board).getAllByText(/need attention/i)).toHaveLength(1)
    expect(within(board).queryByRole('button', { name: /Coverage and check times/i })).not.toBeInTheDocument()
    expect(screen.queryByText('Add to this Site')).not.toBeInTheDocument()
  })

  it('opens flagged rows from the summary and returns to all areas', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    fireEvent.click(within(board).getByRole('button', { name: '3 Flags', exact: true }))
    expect(within(board).getByRole('button', { name: 'Open Pricing page is not loading' })).toBeVisible()
    expect(within(board).getByRole('button', { name: 'Open Contact page loads too slowly' })).toBeVisible()
    expect(within(board).getByRole('button', { name: `Open ${SAMPLE_FLAGS.checkout.title}` })).toBeVisible()
    expect(within(board).queryByRole('button', { name: 'Open Security' })).not.toBeInTheDocument()
    fireEvent.click(within(board).getByRole('button', { name: 'Open Pricing page is not loading' }))
    expect(within(screen.getByRole('dialog')).getByRole('heading', { name: S.availabilityTitle })).toBeVisible()
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    fireEvent.click(within(board).getByRole('button', { name: S.allAreas }))
    expect(within(board).getByRole('button', { name: 'Open Security' })).toBeVisible()
  })

  it('shows complete mobile and desktop performance results', () => {
    render(<CareHomepage />)
    const dialog = openCategory('Performance')
    expect(within(dialog).getByText('Mobile')).toBeVisible()
    expect(within(dialog).getByText('Desktop')).toBeVisible()
    expect(within(dialog).getAllByText('Checked')).toHaveLength(2)
    expect(within(dialog).getByText('0 Flags')).toBeVisible()
  })

  it('shows a complete illustrative website report', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    for (const card of S.categories) expect(within(board).getByRole('button', { name: `Open ${card.name}` })).toBeVisible()
    expect(within(board).getAllByText('0 Flags')).toHaveLength(6)
    expect(within(board).queryByText('Partial')).not.toBeInTheDocument()
    expect(within(board).queryByText('Main content loads in 1.8s')).not.toBeInTheDocument()
    expect(within(board).queryByText('Pages use HTTPS')).not.toBeInTheDocument()
    expect(screen.queryByText('Illustrative results and schedule. Explore any area for more detail.')).not.toBeInTheDocument()
  })

  it('keeps healthy results bounded to their evidence scope', () => {
    render(<CareHomepage />)
    const dialog = openCategory('Search')
    expect(within(dialog).getByText('Page titles')).toBeVisible()
    expect(within(dialog).getByText('Search rankings')).toBeVisible()
    expect(within(dialog).getByText('Outside coverage')).toBeVisible()
    expect(within(dialog).getByRole('link', { name: /Search Console context/ })).toHaveAttribute('href', '/integrations#search-console')
  })

  it('uses pricing HTTP evidence only for the availability Flag', () => {
    render(<CareHomepage />)
    let dialog = openCategory('Pages')
    expect(within(dialog).queryByRole('img')).not.toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for /pricing' }))
    dialog = screen.getByRole('dialog')
    expect(within(dialog).getByRole('img', { name: S.availabilityAlt })).toHaveAttribute('data-src', '/marketing/evidence/pricing-unavailable.png')
    expect(within(dialog).queryByRole('img', { name: C.flag.cropAlt })).not.toBeInTheDocument()
    expect(within(dialog).queryByText(S.unresolved)).not.toBeInTheDocument()
    expect(within(dialog).getByRole('link', { name: '/pricing' })).toHaveAttribute('href', S.sources.http)
    expect(within(dialog).queryByRole('button', { name: S.recoveryAction })).not.toBeInTheDocument()
  })

  it('keeps Signup unconfigured and shows scoped checkout recovery only for Checkout', () => {
    render(<CareHomepage />)
    let dialog = openCategory('Conversion')
    expect(within(dialog).getByText('Safe Signup')).toBeVisible()
    expect(within(dialog).getByText('Not configured')).toBeVisible()
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for Add to cart' }))
    dialog = screen.getByRole('dialog')
    expect(within(dialog).getByText(SAMPLE_FLAGS.checkout.observed)).toBeVisible()
    expect(within(dialog).getByText(SAMPLE_FLAGS.checkout.expected)).toBeVisible()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Back to Conversion' }))
    expect(within(dialog).getByText('Safe Signup')).toBeVisible()
  })

  it('opens and copies the second Pages issue independently, with rechecking in category depth', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true })
    render(<CareHomepage />)
    let dialog = openCategory('Pages')
    expect(within(dialog).getByRole('link', { name: 'Recheck Pages' })).toHaveAttribute('href', '#analyze')
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for /contact' }))
    dialog = screen.getByRole('dialog')
    expect(within(dialog).getByRole('heading', { name: 'Contact page loads too slowly' })).toBeVisible()
    expect(within(dialog).getByText(SAMPLE_FLAGS.contact.observed)).toBeVisible()
    expect(within(dialog).getByRole('link', { name: '/contact' })).toHaveAttribute('href', SAMPLE_FLAGS.contact.url)
    expect(within(dialog).queryByRole('img')).not.toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: S.sampleCopy }))
    await waitFor(() => expect(writeText).toHaveBeenCalledWith(SAMPLE_FLAGS.contact.prompt))
    fireEvent.click(within(dialog).getByRole('button', { name: 'Back to Pages' }))
    expect(within(dialog).getByRole('button', { name: 'View Flag for /pricing' })).toBeVisible()
    expect(within(dialog).getByRole('button', { name: 'View Flag for /contact' })).toBeVisible()
  })

  it('keeps concise scope in category depth', () => {
    render(<CareHomepage />)
    const dialog = openCategory('Pages')
    expect(within(dialog).getByText(S.categories[0].scope)).toBeVisible()
    expect(within(dialog).queryByText(S.sources.http)).not.toBeInTheDocument()
    expect(watchableOutcomeKinds()).toEqual(['CHECKOUT', 'SIGNUP', 'AVAILABILITY'])
    expect(C.monitoring.notScheduled).toBe('Not scheduled')
  })

  it('shows dated sample scheduling and never suggests a UI control runs verification', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    expect(within(board).queryByText(C.monitoring.summary)).not.toBeInTheDocument()
    expect(within(board).queryByRole('button', { name: C.monitoring.action })).not.toBeInTheDocument()
    fireEvent.click(within(board).getByRole('button', { name: S.navigation.monitoring, exact: true }))
    const monitoring = board
    expect(within(monitoring).getByText('Flags over time')).toBeVisible()
    expect(within(monitoring).getByRole('list', { name: 'Check history' })).toBeVisible()
    expect(within(monitoring).getAllByText('Check completed')).toHaveLength(5)
    expect(within(monitoring).getByRole('button', { name: S.availabilityTitle })).toBeVisible()
    expect(within(monitoring).queryByRole('button', { name: 'Edit schedule' })).not.toBeInTheDocument()
    expect(within(monitoring).queryByText('Verified recovery')).not.toBeInTheDocument()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Verify fix/ })).not.toBeInTheDocument()
    expect(screen.queryByText('Just now')).not.toBeInTheDocument()
  })

  it('links the intro to MCP setup and provides settings in the sample navigation', () => {
    render(<CareHomepage />)
    expect(screen.getByRole('link', { name: 'MCP', exact: true }).closest('p')).toHaveTextContent(`${S.subtitle} Use the MCP to work directly from your AI.`)
    expect(screen.getByRole('link', { name: 'MCP', exact: true })).toHaveAttribute('href', '/dashboard/mcp-setup')
    const board = screen.getByRole('region', { name: C.boardAria })
    const nav = within(board).getByRole('navigation', { name: S.navigationLabel })
    expect(within(nav).getAllByRole('button').map(button => button.getAttribute('aria-label'))).toEqual(['Site', 'Monitoring', 'Integrations', 'Settings'])
    fireEvent.click(within(nav).getByRole('button', { name: 'Settings', exact: true }))
    expect(within(board).getByRole('heading', { name: 'Settings' })).toBeVisible()
    fireEvent.change(within(board).getByRole('combobox', { name: 'Email me' }), { target: { value: 'OFF' } })
    expect(within(board).getByRole('checkbox', { name: /verified as recovered/ })).toBeDisabled()
    fireEvent.click(within(board).getByRole('button', { name: 'Daily', exact: true }))
    expect(within(screen.getByRole('dialog')).getByRole('combobox', { name: 'Check frequency' })).toHaveValue('daily')
  })

  it('opens the sample integration list from the board navigation', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    fireEvent.click(within(board).getByRole('button', { name: S.navigation.integrations }))
    expect(within(board).getByRole('heading', { name: S.navigation.integrations })).toBeVisible()
    expect(within(board).getByText('Shopify')).toBeVisible()
    expect(within(board).getByText('Google Analytics')).toBeVisible()
    expect(within(board).getByRole('button', { name: 'Connect Google Analytics' })).toBeVisible()
    expect(within(board).getByRole('button', { name: 'Settings for Shopify' })).toBeVisible()
    expect(within(board).queryByText('Available')).not.toBeInTheDocument()
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('connects and manages a suggested integration in the preview', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    fireEvent.click(within(board).getByRole('button', { name: S.navigation.integrations }))
    expect(within(board).getByRole('heading', { name: 'Suggested for this website' })).toBeVisible()
    fireEvent.click(within(board).getByRole('button', { name: 'Connect Google Analytics' }))
    let dialog = screen.getByRole('dialog')
    expect(within(dialog).getByText('This connection is part of the preview. Changes stay in this sample.')).toBeVisible()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Connect in preview' }))
    fireEvent.click(within(board).getByRole('button', { name: 'Settings for Google Analytics' }))
    dialog = screen.getByRole('dialog')
    fireEvent.click(within(dialog).getByRole('button', { name: 'Disconnect in preview' }))
    expect(within(board).getByRole('button', { name: 'Connect Google Analytics' })).toBeVisible()
    expect(within(board).getByRole('button', { name: 'Settings for Shopify' })).toBeVisible()
  })

  it('opens a Flag from its check in the monitoring timeline', () => {
    render(<CareHomepage />)
    const board = screen.getByRole('region', { name: C.boardAria })
    fireEvent.click(within(board).getByRole('button', { name: S.navigation.monitoring, exact: true }))
    fireEvent.click(within(board).getByRole('button', { name: SAMPLE_FLAGS.contact.title }))
    expect(within(screen.getByRole('dialog')).getByRole('heading', { name: SAMPLE_FLAGS.contact.title })).toBeVisible()
  })

  it('copies scoped guidance without resolving the Flag and restores the category opener', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true })
    render(<><CareHomepage /><Toaster /></>)
    const opener = screen.getByRole('button', { name: 'Open Pages' }); opener.focus()
    let dialog = openCategory('Pages')
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for /pricing' }))
    dialog = screen.getByRole('dialog')
    fireEvent.click(within(dialog).getByRole('button', { name: S.sampleCopy }))
    await waitFor(() => expect(writeText).toHaveBeenCalledWith(S.availabilityPrompt))
    expect(within(dialog).queryByText(S.unresolved)).not.toBeInTheDocument()
    await waitFor(() => expect(screen.getByText('Fix prompt copied')).toBeInTheDocument())
    expect(screen.getByRole('link', { name: 'Set up MCP' })).toHaveAttribute('href', '/dashboard/mcp-setup')
    fireEvent.click(within(dialog).getByRole('button', { name: 'Close' }))
    await waitFor(() => expect(opener).toHaveFocus())
  })

  it('copies directly from a Flag shortcut and offers MCP setup in the confirmation', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true })
    render(<><CareHomepage /><Toaster /></>)
    fireEvent.click(screen.getByRole('button', { name: 'Copy fix prompt for Pricing page is not loading' }))
    await waitFor(() => expect(writeText).toHaveBeenCalledWith(S.availabilityPrompt))
    await waitFor(() => expect(screen.getByText('Fix prompt copied')).toBeInTheDocument())
    expect(screen.getByRole('link', { name: 'Set up MCP' })).toHaveAttribute('href', '/dashboard/mcp-setup')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('provides readable guidance if clipboard access fails', async () => {
    Object.defineProperty(navigator, 'clipboard', { value: { writeText: vi.fn().mockRejectedValue(new Error('denied')) }, configurable: true })
    render(<CareHomepage />)
    const dialog = openCategory('Pages')
    fireEvent.click(within(dialog).getByRole('button', { name: 'View Flag for /pricing' }))
    fireEvent.click(within(dialog).getByRole('button', { name: S.sampleCopy }))
    await waitFor(() => expect(within(dialog).getByRole('textbox', { name: S.guidanceLabel })).toHaveValue(S.availabilityPrompt))
  })

  it('explains all eight product areas immediately after the sample without disclaimer rows', () => {
    render(<CareHomepage />)
    const coverage = screen.getByRole('region', { name: C.checks.title })
    expect(C.checks.areas.map(area => area.id).sort()).toEqual([...SITE_CARD_AREAS].sort())
    expect(C.checks.areas).toHaveLength(8)
    expect(C.checks.title).toContain(`${C.checks.areas.length} areas`)
    for (const area of C.checks.areas) {
      expect(within(coverage).getByRole('button', { name: C.checks.explore(area.name) })).toBeVisible()
      expect(within(coverage).getByText(area.benefit)).toBeVisible()
    }
    expect(within(coverage).getByText('404')).toBeVisible()
    expect(within(coverage).getByText(C.checks.previews.conversion.result)).toBeVisible()
    expect(within(coverage).getByText(C.checks.previews.conversion.product)).toBeVisible()
    expect(within(coverage).queryByText('Cart remains empty')).not.toBeInTheDocument()
    expect(within(coverage).getByRole('img', { name: C.checks.previews.search.imageAlt })).toHaveAttribute('data-src', C.checks.previews.search.image)
    expect(within(coverage).getByText(C.checks.previews.search.title)).toBeVisible()
    const tracking = within(coverage).getByRole('button', { name: C.checks.explore('Tracking') }).closest('article')!
    for (const page of C.checks.previews.tracking.pages) expect(within(tracking).getByText(page.page)).toBeVisible()
    expect(within(tracking).queryByText('/products')).not.toBeInTheDocument()
    expect(within(coverage).getByText('Flag what prevents you from making money.')).toBeVisible()
    expect(within(coverage).queryByText(/Stripe|Payment form missing|Script blocked/)).not.toBeInTheDocument()
    expect(screen.queryByText('Illustrative check examples')).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: C.story.title })).not.toBeInTheDocument()
    expect(screen.queryByText(C.story.example.failedTitle)).not.toBeInTheDocument()
    expect(document.getElementById('product')?.nextElementSibling).toBe(coverage)
  })

  it('opens complete marketing coverage for every area instead of sample results', () => {
    render(<CareHomepage />)
    for (const area of C.checks.areas) {
      fireEvent.click(screen.getByRole('button', { name: C.checks.explore(area.name) }))
      const dialog = screen.getByRole('dialog')
      expect(within(dialog).getByRole('heading', { name: C.checks.detailTitle(area.name) })).toBeVisible()
      for (const group of area.groups) {
        expect(within(dialog).getByRole('heading', { name: group.title })).toBeVisible()
        for (const check of group.checks) expect(within(dialog).getByText(check)).toBeVisible()
      }
      expect(within(dialog).queryByRole('button', { name: S.sampleCopy })).not.toBeInTheDocument()
      expect(within(dialog).queryByText('0 Flags')).not.toBeInTheDocument()
      expect(within(dialog).queryByText('15 minutes ago')).not.toBeInTheDocument()
      expect(within(dialog).getByRole('link', { name: C.checks.detailAction })).toHaveAttribute('href', '#analyze')
      fireEvent.click(within(dialog).getByRole('button', { name: 'Close' }))
    }
  })

  it('shows experience coverage and returns focus to the marketing card', async () => {
    render(<CareHomepage />)
    const opener = screen.getByRole('button', { name: C.checks.explore('Conversion') })
    opener.focus()
    fireEvent.click(opener)
    const dialog = screen.getByRole('dialog')
    expect(within(dialog).getByRole('heading', { name: 'Customer experience' })).toBeVisible()
    expect(within(dialog).getByText('Mobile menus and pricing navigation')).toBeVisible()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Close' }))
    await waitFor(() => expect(opener).toHaveFocus())
  })

  it('copies the displayed pricing-page guidance without resolving the sample Flag', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true })
    render(<CareHomepage />)
    const handoff = screen.getByRole('region', { name: C.story.guidanceTitle })
    for (const fact of C.actions.promptFacts) expect(within(handoff).getByText(fact.value)).toBeVisible()
    expect(within(handoff).getByRole('heading', { name: C.actions.promptTitle })).toBeVisible()
    fireEvent.click(within(handoff).getByRole('button', { name: C.story.copy }))
    await waitFor(() => expect(writeText).toHaveBeenCalledWith(S.availabilityPrompt))
    expect(within(handoff).getByRole('status')).toHaveTextContent(C.story.copied)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '3 Flags', exact: true })).toBeVisible()
  })

  it('keeps the handoff prompt available inline when clipboard access fails', async () => {
    Object.defineProperty(navigator, 'clipboard', { value: { writeText: vi.fn().mockRejectedValue(new Error('denied')) }, configurable: true })
    render(<CareHomepage />)
    const handoff = screen.getByRole('region', { name: C.story.guidanceTitle })
    fireEvent.click(within(handoff).getByRole('button', { name: C.story.copy }))
    await waitFor(() => expect(within(handoff).getByRole('textbox', { name: S.guidanceLabel })).toHaveValue(S.availabilityPrompt))
    expect(within(handoff).getByRole('status')).toHaveTextContent(S.copyFailed)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('places benefits above the hero entry and AI tools below it', () => {
    render(<CareHomepage />)
    const guides = screen.getByRole('list', { name: C.actions.editorGuidesLabel })
    expect(within(guides).getAllByRole('link')).toHaveLength(8)
    expect(within(guides).getByRole('link', { name: 'Cursor' })).toHaveAttribute('href', '/docs/integrations#cursor')
    expect(within(guides).getByRole('link', { name: 'Codex' })).toHaveAttribute('href', '/docs/integrations#codex')
    const hero = guides.closest('section')!
    const entry = hero.querySelector('#analyze')!
    expect(entry.compareDocumentPosition(guides)).toBe(Node.DOCUMENT_POSITION_FOLLOWING)
    expect(screen.queryByText('No credit card required')).not.toBeInTheDocument()
    const benefits = screen.getByRole('list', { name: 'What FixFlags does' })
    expect(benefits.closest('section')).toBe(hero)
    expect(benefits.compareDocumentPosition(entry)).toBe(Node.DOCUMENT_POSITION_FOLLOWING)
    expect(benefits.compareDocumentPosition(screen.getByRole('region', { name: C.boardAria }))).toBe(Node.DOCUMENT_POSITION_FOLLOWING)
  })

  it('shows the current and proposed integrations and opens their details', () => {
    render(<CareHomepage />)
    const section = screen.getByRole('region', { name: C.integrations.title })
    expect(INTEGRATIONS_PAGE.items).toHaveLength(10)
    for (const item of INTEGRATIONS_PAGE.items) {
      const link = within(section).getByRole('link', { name: new RegExp(item.title) })
      expect(link).toHaveAttribute('href', `/integrations#${item.id}`)
      expect(link).toHaveTextContent(item.status === 'available' ? INTEGRATIONS_PAGE.availableLabel : INTEGRATIONS_PAGE.proposedLabel)
    }
  })

})
