export const REVIEW_PREVIEW = {
  reviewedHost: 'fixflags.com',
  demoHost: 'yourproduct.com',
  score: 72,
  scoreStatus: 'Needs work',
  completedAtLabel: 'Scanned 2 minutes ago',
  scoreLabel: 'Overall score',
  pendingScoreLabel: 'Score pending',
  progressLabel: 'Review progress',
  flagsSummary: '7 high-impact flags',
  steps: [
    { label: 'Site captured', detail: 'Homepage', state: 'done' },
    { label: 'Checks complete', detail: '24 checks', state: 'done' },
    { label: 'Flags found', detail: '7', state: 'active' },
    { label: 'Fix prompts ready', detail: 'Cursor-ready', state: 'pending' },
    { label: 'Review ready', detail: 'After scoring', state: 'pending' },
  ],
  flags: [
    {
      severity: 'High impact',
      rubric: 'Message',
      title: 'Hero value is unclear',
      description: 'Visitors cannot understand what you do or why it matters in 5 seconds.',
      evidence: '"Build something amazing with AI"',
      impact: 'High',
      affects: ['Conversion', 'Trust'],
      fix: 'Rewrite the hero headline to name the audience and outcome in one sentence. Replace generic AI copy with a specific value prop and a single primary CTA above the fold.',
    },
    {
      severity: 'High impact',
      rubric: 'Experience',
      title: 'Primary CTA is easy to miss',
      description: 'The main action competes with a secondary button and does not feel like the obvious next step.',
      evidence: 'Two equal-weight actions appear in the hero',
      impact: 'High',
      affects: ['Conversion', 'Flow'],
      fix: 'Make one primary CTA visually dominant and move the secondary action to a quieter outline treatment with clearer copy.',
    },
    {
      severity: 'High impact',
      rubric: 'Reach',
      title: 'Social preview needs a stronger promise',
      description: 'Shared links should tell people what they get before they click.',
      evidence: 'Preview title repeats the product name only',
      impact: 'High',
      affects: ['Sharing', 'SEO'],
      fix: 'Update the Open Graph title and description to name the audience, outcome, and proof point in plain language.',
    },
    {
      severity: 'Important',
      rubric: 'Message',
      title: 'Proof comes too late',
      description: 'Visitors see the claim before they see why they should trust it.',
      evidence: 'Customer proof starts below the first viewport',
      impact: 'Medium',
      affects: ['Trust', 'Conversion'],
      fix: 'Move one concrete proof point into the hero: customer count, recognizable workflow, or before/after result.',
    },
    {
      severity: 'Important',
      rubric: 'Experience',
      title: 'Mobile hero feels crowded',
      description: 'The hero stacks copy, actions, social proof, and logos too tightly on small screens.',
      evidence: '375px viewport shows four competing content groups',
      impact: 'Medium',
      affects: ['Mobile', 'Clarity'],
      fix: 'Reduce the mobile hero to headline, one support line, primary CTA, and one proof row before the fold.',
    },
    {
      severity: 'Important',
      rubric: 'Reach',
      title: 'Metadata could be more specific',
      description: 'Search snippets should describe the concrete review output, not just the category.',
      evidence: 'Description uses broad product language',
      impact: 'Medium',
      affects: ['SEO', 'Sharing'],
      fix: 'Rewrite the meta description around the outcome: Flags, screenshots, and fix prompts for AI-built sites.',
    },
    {
      severity: 'Polish',
      rubric: 'Experience',
      title: 'Logo row distracts from the next step',
      description: 'Too many small brand names pull attention away from the CTA.',
      evidence: 'Four tool names appear directly under the hero proof row',
      impact: 'Low',
      affects: ['Focus', 'Scanability'],
      fix: 'Move the tool row below the first divider and use lower-contrast text so the primary CTA remains the visual anchor.',
    },
  ],
} as const
