/** Every deterministic checkId implemented in lib/audit/checks/*. */
export const ALL_CHECK_IDS = [
  // metadata-checks.ts
  'title-missing',
  'title-too-short',
  'title-too-long',
  'description-missing',
  'description-too-short',
  'description-too-long',
  'og-image-missing',
  'og-image-broken',
  'og-title-missing',
  'og-description-missing',
  'viewport-missing',
  'lang-missing',
  'canonical-missing',
  'robots-blocks-indexing',
  'favicon-missing',
  // performance.ts
  'perf-score-critical',
  'perf-score-poor',
  'lcp-critical',
  'lcp-poor',
  'cls-critical',
  'cls-poor',
  'render-blocking',
  'unused-js-large',
  'unused-css-large',
  'unoptimized-images',
  'inp-critical',
  'inp-poor',
  // accessibility.ts
  'images-missing-alt',
  'form-inputs-no-label',
  'buttons-no-text',
  'links-no-text',
  'iframe-no-title',
  'tabindex-positive',
  'color-contrast-poor',
  'skip-link-missing',
  'keyboard-nav-trap',
  'focus-visible-missing',
  // seo.ts
  'h1-missing',
  'h1-multiple',
  'no-structured-data',
  'sitemap-missing',
  'robots-txt-missing',
  'broken-internal-links',
  'broken-page-anchors',
  // trust.ts
  'no-https',
  'no-privacy-policy',
  'no-contact-info',
  'cookie-consent-absent',
  'console-errors-critical',
  'console-errors-some',
  // mobile.ts
  'mobile-perf-critical',
  'mobile-perf-poor',
  'tap-targets-small',
  'mobile-lcp-critical',
  // content.ts
  'h1-generic',
  'no-cta-detected',
  'heading-hierarchy-missing',
  // layout.ts
  'cta-below-fold-mobile',
  // interaction.ts
  'loading-indicator-stuck',
  'loading-state-slow',
  'motion-ignores-reduced-preference',
  'form-inputs-zoom-mobile',
  // cta-focus.ts
  'competing-ctas',
  // slop.ts
  'placeholder-copy-detected',
  'template-default-copy',
  'unreplaced-template-token',
  'cta-dead-link',
  'social-proof-unverifiable',
  // content.ts
  'form-missing-validation',
  // measurement.ts
  'measurement-ga-gtm-posthog-missing',
  // auth-checkout.ts
  'checkout-link-dead',
  'auth-page-broken',
  // security.ts
  'security-mixed-content',
  // security-headers.ts
  'security-csp-missing',
  'security-csp-unsafe-inline',
  'security-hsts-missing',
  'security-hsts-too-short',
  'security-frame-options-missing',
  'security-frame-options-too-permissive',
  'security-content-type-options-missing',
  // visual-polish.ts
  'visual-radius-inconsistent',
  'visual-typography-sprawl',
  // messaging-clarity.ts
  'messaging-weak-value-prop',
  'messaging-jargon-overload',
  'messaging-no-audience',
  'messaging-long-sentences',
  'messaging-headline-too-short',
  // conversion-friction.ts
  'friction-no-commitment-path',
  'friction-trial-commitment-unclear',
  'friction-form-too-many-fields',
  'friction-no-risk-reversal',
  'friction-no-social-proof',
  // trust-psychology.ts
  'trust-no-authority-signals',
  'trust-testimonial-quality',
  'trust-unsupported-claims',
  'trust-no-direct-contact',
  'trust-no-internal-links',
  // visual-hierarchy.ts
  'hierarchy-competing-actions',
  'hierarchy-too-many-fonts',
  'hierarchy-no-sections',
  'hierarchy-no-headline',
  'hierarchy-information-density',
  // mobile-ux-quality.ts
  'mobile-input-zoom',
  'mobile-cta-thumb-zone',
  'mobile-cta-weak-label',
  'mobile-stuck-loading',
  'mobile-load-delay-content',
  // flow.ts
  'flow-no-cta-found',
  'flow-cta-unclickable',
  'flow-cta-404',
  'flow-cta-dead-end',
  'flow-cta-external-leave',
  'flow-pricing-nav-broken',
  'flow-mobile-menu-broken',
  'flow-form-no-validation',
  'flow-form-slow-feedback',
  'scroll-ghost-sections',
  'flow-cta-blank-destination',
  'flow-cta-stuck-loading',
  'flow-cta-destination-no-trust',
  'flow-destination-no-headline',
  'flow-destination-no-cta',
  'flow-cta-message-mismatch',
  'flow-destination-cta-overload',
  'flow-destination-stuck-loading',
  'flow-destination-no-privacy',
  'flow-destination-slow-load',
  // slow-replay.ts
  'slow-3g-blank-screen',
  'slow-3g-cta-delayed',
  // journey review
  'journey-first-visit-unclear-value-prop',
  'journey-first-visit-hidden-cta',
  'journey-first-visit-dead-end',
  'journey-first-visit-nav-broken',
  'journey-first-visit-destination-no-headline',
  'journey-first-visit-destination-no-next-action',
  'journey-pricing-evaluation-unclear-value-prop',
  'journey-pricing-evaluation-hidden-cta',
  'journey-pricing-evaluation-dead-end',
  'journey-pricing-evaluation-nav-broken',
  'journey-pricing-evaluation-destination-no-headline',
  'journey-pricing-evaluation-destination-no-next-action',
  'journey-signup-unclear-value-prop',
  'journey-signup-hidden-cta',
  'journey-signup-dead-end',
  'journey-signup-nav-broken',
  'journey-signup-no-form',
  'journey-signup-too-many-fields',
  'journey-contact-not-found',
  // corridor consistency
  'corridor-og-title-drift',
  'corridor-og-description-drift',
  // network-engagement.ts / overlay.ts
  'api-engagement-unauthorized',
  'api-engagement-server-error',
  'form-submit-api-unauthorized',
  'form-submit-api-server-error',
  'overlay-blocks-nav',
  'overlay-blocks-cta',
  'overlay-blocks-form',
] as const

export type CheckId = (typeof ALL_CHECK_IDS)[number]

export const CHECK_ID_COUNT = ALL_CHECK_IDS.length
