import { gradeFromScore } from '@/lib/audit/scoring'
import { isObjectiveArea } from '@/lib/audit/score-display'
import { areaLabel } from '@/lib/utils'
import { SITE_URL } from '@/lib/marketing/copy'
import { AREA_ORDER } from '@/lib/audit/constants'

interface ExportFinding {
  severity: string
  problem: string
  area?: string
}

interface ExportArea {
  name: string
  grade: string | null
  score: number | null
}

interface ExportAuditInput {
  auditId: string
  url: string
  score: number | null
  verdict?: string | null
  isPublic?: boolean
  areas: ExportArea[]
  findings: ExportFinding[]
}

const SEVERITY_ORDER: Record<string, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
  INFO: 4,
}

function formatAreaScore(area: ExportArea): string {
  if (isObjectiveArea(area.name) && area.score != null) {
    return `${area.score}/100 (${area.grade ?? '-'})`
  }
  return area.grade ?? '-'
}

export function buildAuditExportSummary(audit: ExportAuditInput): string {
  const hostname = (() => {
    try {
      return new URL(audit.url).hostname
    } catch {
      return audit.url
    }
  })()

  const overallGrade = audit.score != null ? gradeFromScore(audit.score) : null
  const scoreLine =
    audit.score != null
      ? `**Overall:** ${audit.score}/100 (Grade ${overallGrade})`
      : '**Overall:** Score unavailable'

  const orderedAreas = AREA_ORDER.map((name) =>
    audit.areas.find((a) => a.name === name)
  ).filter(Boolean) as ExportArea[]

  const areaLines = orderedAreas
    .map((a) => `- ${areaLabel(a.name)}: ${formatAreaScore(a)}`)
    .join('\n')

  const topFindings = [...audit.findings]
    .sort((a, b) => (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9))
    .slice(0, 3)

  const findingLines =
    topFindings.length > 0
      ? topFindings
          .map((f, i) => {
            const area = f.area ? ` (${areaLabel(f.area)})` : ''
            return `${i + 1}. [${f.severity}] ${f.problem}${area}`
          })
          .join('\n')
      : 'No priority findings listed.'

  const verdict = audit.verdict ? `\n**Summary:** ${audit.verdict}\n` : ''

  return [
    `# QualityOS Audit - ${hostname}`,
    '',
    scoreLine,
    verdict,
    audit.isPublic ? `Share link: ${SITE_URL}/audit/${audit.auditId}` : '',
    '## Area scores',
    areaLines,
    '',
    '## Top findings',
    findingLines,
    '',
    `Full report: ${SITE_URL}/audit/${audit.auditId}`,
    '',
    '_Generated by QualityOS - automated audit with evidence and fix prompts._',
  ].join('\n')
}

export function collectFindingsFromAreas(
  areas: Array<{ name: string; findings?: ExportFinding[] }>
): ExportFinding[] {
  return areas.flatMap((area) =>
    (area.findings ?? []).map((f) => ({ ...f, area: area.name }))
  )
}
