import { gradeFromScore } from '@/lib/audit/scoring'
import { formatScoreInline } from '@/lib/audit/score-display'
import { displayVerdict } from '@/lib/audit/verdict'
import { rubricLabel, shareStatusLabel } from '@/lib/utils'
import { BRAND, SITE_URL } from '@/lib/marketing/copy'
import { RUBRIC_ORDER, type RubricName } from '@/lib/audit/constants'
import {
  buildRubricInput,
  computeAllRubricStatuses,
  computeShareStatus,
} from '@/lib/audit/rubric'

interface ExportFlag {
  severity: string
  problem: string
  rubric?: string
}

interface ExportRubricRow {
  name: string
  grade: string | null
  score: number | null
}

interface ExportAuditInput {
  auditId: string
  url: string
  score: number | null
  verdict?: string | null
  isPublic?: boolean
  rubrics: ExportRubricRow[]
  flags: ExportFlag[]
}

const SEVERITY_ORDER: Record<string, number> = {
  CRITICAL: 0,
  IMPORTANT: 1,
  POLISH: 2,
}

function formatRubricScore(row: ExportRubricRow): string {
  if (row.score != null) {
    return formatScoreInline(row.score, row.grade ?? gradeFromScore(row.score))
  }
  return row.grade ?? '-'
}

export function buildAuditExportSummary(audit: ExportAuditInput): string {
  const hostname = (() => {
    try {
      return new URL(audit.url).hostname
    } catch {
      return audit.url
    }
  })()

  const overallGrade = audit.score != null ? gradeFromScore(audit.score) : null
  const scoreLine =
    audit.score != null
      ? `**Overall:** ${audit.score}/100 (Grade ${overallGrade})`
      : '**Overall:** Score unavailable'

  const rubricRows = audit.rubrics
  const flags = audit.flags
  const rubricInput = buildRubricInput(rubricRows, flags)
  const rubrics = computeAllRubricStatuses(rubricInput)
  const shareStatus = computeShareStatus(rubrics, flags)

  const shareLine = `**Share status:** ${shareStatusLabel(shareStatus)}`

  const rubricLines = RUBRIC_ORDER.map((name) => {
    const row = rubrics.find((r) => r.name === name)
    const source = rubricRows.find((r) => r.name === name)
    if (!row || !source) return ''
    const issueCount = row.criticalCount + row.importantCount
    return `### ${rubricLabel(name)}: ${row.status} (${issueCount} priority flags)\n  - Score: ${formatRubricScore(source)}`
  }).join('\n')

  const topFlags = [...flags]
    .sort((a, b) => (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9))
    .slice(0, 3)

  const flagLines =
    topFlags.length > 0
      ? topFlags
          .map((flag, i) => {
            const rubric = flag.rubric ? rubricLabel(flag.rubric as RubricName) : ''
            const suffix = rubric ? ` (${rubric})` : ''
            return `${i + 1}. [${flag.severity}] ${flag.problem}${suffix}`
          })
          .join('\n')
      : 'No priority flags listed.'

  const verdictText = displayVerdict(audit.verdict)
  const verdict = verdictText ? `\n**Summary:** ${verdictText}\n` : ''

  return [
    `# ${BRAND.exportPrefix} - ${hostname}`,
    '',
    scoreLine,
    verdict,
    audit.isPublic ? `Share link: ${SITE_URL}/report/${audit.auditId}` : '',
    '',
    shareLine,
    '',
    '## Rubrics',
    rubricLines,
    '',
    '## Top flags',
    flagLines,
    '',
    `Full report: ${SITE_URL}/report/${audit.auditId}`,
    '',
    `_Generated by ${BRAND.name}. Automated QA with evidence and fix prompts._`,
  ].join('\n')
}

export function collectFlagsFromRubrics(
  rubrics: Array<{ name: string; flags?: ExportFlag[] }>
): ExportFlag[] {
  return rubrics.flatMap((rubric) =>
    (rubric.flags ?? []).map((flag) => ({ ...flag, rubric: rubric.name }))
  )
}
