export const FIX_ACTION_COPY = {
  cursorMcpLabel: 'Connect Cursor MCP',
  cursorMcpAriaLabel: 'Connect Cursor MCP to run FixFlags from your editor',
  cursorMcpAuthRedirect: '/sign-in?next=/docs/mcp',
  promptCopyLabel: 'Copy fix prompt',
  promptCopyAriaLabel: 'Copy fix prompt to clipboard',
  promptCopiedLabel: 'Copied!',
  lovableCopyLabel: 'Copy for Lovable',
  lovableCopyAriaLabel: 'Copy visual/design fix prompt for Lovable',
  boltCopyLabel: 'Copy for Bolt',
  boltCopyAriaLabel: 'Copy file-level diff prompt for Bolt.new',
  claudeCodeCopyLabel: 'Copy for Claude Code',
  claudeCodeCopyAriaLabel: 'Copy terminal-ready instruction for Claude Code',
  windsurfCopyLabel: 'Copy for Windsurf',
  windsurfCopyAriaLabel: 'Copy fix prompt for Windsurf IDE',
  agentPromptLabel: 'Agent prompt',
  agentPromptAriaLabel: 'Universal AI agent fix prompt',
  branchEditLabel: 'Open in repo',
  branchEditAriaLabel: 'Open this fix as a branch edit on your repository',
  exportAllLabel: 'Export all fixes',
  exportAllAriaLabel: 'Export all fix prompts as a single document',
} as const
