/** Lightweight report projection shared by SSR handoff and status polling. */
export const progressiveAuditSelect = {
  id: true,
  status: true,
  progress: true,
  progressDetail: true,
  score: true,
  pageType: true,
  verdict: true,
  errorMsg: true,
  failureCode: true,
  pipelineVersion: true,
  reportCompleteness: true,
  startedAt: true,
  completedAt: true,
  updatedAt: true,
  createdAt: true,
  url: true,
  userId: true,
  isPublic: true,
  parentId: true,
  aiReviewAt: true,
  triageAt: true,
  includeAi: true,
  journeyReviewIncluded: true,
  journeyReviewAt: true,
  performanceData: true,
  productContract: true,
  screenshots: {
    select: { device: true, url: true, width: true, height: true },
  },
  rubrics: {
    select: { name: true, grade: true, score: true, status: true },
    orderBy: { name: 'asc' as const },
  },
  flags: {
    select: {
      id: true,
      severity: true,
      problem: true,
      rubric: true,
      checkId: true,
      source: true,
      pageUrl: true,
    },
    orderBy: { position: 'asc' as const },
  },
} as const
