import { PRICING_COPY } from './terminology'

export const AUTH = {
  reportGate: {
    title: 'Your site review is underway',
    subtitle: (hostname?: string | null) =>
      hostname
        ? `Create a free account while FixFlags reviews ${hostname}. Your report will be saved here.`
        : 'Create a free account while FixFlags reviews your site. Your report will be saved here.',
    preparingOptions: 'Preparing sign-in options',
    backHome: 'Back to home',
    exit: 'Leave this report',
    saving: 'Saving your report',
    savingBody: 'Your account is ready. We are attaching this review and preparing the fix prompts.',
  },
  reportContext: {
    title: (hostname: string) => `Save ${hostname}`,
    loadingTitle: 'Save this report',
    body: 'Get every fix prompt and keep this report for update reviews on the same URL.',
    backCta: 'Back to report',
    saving: (hostname?: string | null) => hostname ? `Saving ${hostname}` : 'Saving your report',
    unlocking: 'Preparing your fix list',
    redirecting: 'Your report is saved. Taking you back to the fixes.',
    waiting: 'This will only take a moment.',
    saveError: 'Your account is ready, but we could not save your report yet.',
    retryCta: 'Try saving again',
  },
  reportHeader: {
    cta: 'Sign up',
  },
  signIn: {
    title: 'Sign in to your account',
    subtitle: 'Access your reports and continue where you left off',
    trustLine: 'Sign in to access your saved reports and product reviews',
    tryWithoutAccount: 'Try without an account',
    cta: 'Sign in',
    passkeyCta: 'Use a passkey',
    footer: 'Don\u2019t have an account?',
    footerLink: 'Sign up',
    forgotPassword: 'Forgot password?',
    oauthNote: 'Social sign-in is used only to identify your account.',
    error: 'Sign in failed',
    unexpectedError: 'Something went wrong',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    privacyLink: 'Privacy',
    termsLink: 'Terms',
  },
  twoFactor: {
    title: 'Confirm it\u2019s you',
    subtitle: 'Use your passkey to finish signing in',
    passkeyCta: 'Continue with passkey',
    backupLabel: 'Or enter a backup code',
    backupCta: 'Verify backup code',
    backupPlaceholder: 'Backup code',
    trustDevice: 'Remember this device for 30 days',
    backToSignIn: 'Back to sign in',
    invalidBackupCode: 'Invalid backup code',
    backupCodeError: 'Could not verify backup code',
    sessionExpired: 'Your session expired. Sign in again.',
    signInAgain: 'Sign in again',
  },
  security: {
    title: 'Two-factor authentication',
    description:
      'Add a passkey, then require it after your password. Passkeys use your device biometrics or a security key.',
    passkeysTitle: 'Passkeys',
    passkeyItem: 'Passkey',
    passkeysEmpty: 'No passkeys yet. Add one to sign in with this device.',
    addPasskey: 'Add passkey',
    deletePasskey: 'Remove',
    enableTitle: 'Require passkey at sign-in',
    enableDescription:
      'After your password, FixFlags asks for a registered passkey before opening your account.',
    enableCta: 'Enable passkey 2FA',
    disableCta: 'Disable 2FA',
    enabledBadge: 'Enabled',
    disabledBadge: 'Off',
    passwordLabel: 'Current password',
    passwordlessHint: 'OAuth-only accounts can enable without a password.',
    backupCodesTitle: 'Save your backup codes',
    backupCodesBody:
      'Store these somewhere safe. Each code works once if you lose access to your passkeys.',
    backupCodesCopied: 'Backup codes copied',
    copyBackupCodes: 'Copy codes',
    regenerateBackupCodes: 'Generate new backup codes',
    loadError: 'Could not load passkeys',
    addSuccess: 'Passkey added',
    addError: 'Could not add passkey',
    registrationFailed: 'Passkey registration was cancelled or failed',
    removeTitle: 'Remove this passkey?',
    removeDescriptionLast: 'This is your last passkey. Remove it only if you still have backup codes.',
    removeDescription: 'You will not be able to use this passkey to sign in.',
    removeLabel: 'Remove passkey',
    removeSuccess: 'Passkey removed',
    removeError: 'Could not remove passkey',
    passkeyRequired: 'Add a passkey before enabling two-factor authentication',
    enableSuccess: 'Passkey two-factor authentication enabled',
    enableError: 'Could not enable two-factor authentication',
    disableTitle: 'Disable two-factor authentication?',
    disableDescription: 'Password-only sign-in will work again without a passkey challenge.',
    disableLabel: 'Disable 2FA',
    disableSuccess: 'Two-factor authentication disabled',
    disableError: 'Could not disable two-factor authentication',
    backupCodesSuccess: 'New backup codes generated',
    backupCodesError: 'Could not generate backup codes',
    errorTitle: 'Security update failed',
    loadingPasskeys: 'Loading passkeys\u2026',
    synced: 'Synced',
    device: 'Device',
  },
  signUp: {
    title: 'Create your free account',
    subtitle: `${PRICING_COPY.freeProductReviewsPerMonth} product reviews per month. Keep this report and unlock every fix prompt.`,
    fromPricing: `Create your free account: ${PRICING_COPY.freeProductReviewsPerMonth} product reviews per month included.`,
    oauthNote: 'Social sign-in is used only to identify your account.',
    cta: 'Create account',
    footer: 'Already have an account?',
    footerLink: 'Sign in',
    tryWithoutAccount: 'Check a site without an account',
    error: 'Sign up failed',
    unexpectedError: 'Something went wrong',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    planStepsTitle: 'What happens next',
    planTitles: {
      BUILDER: `You\u2019re signing up for Pro, with ${PRICING_COPY.proProductReviewsPerMonth} product reviews per month`,
      TEAM: `You\u2019re signing up for Studio, with ${PRICING_COPY.studioProductReviewsPerMonth} product reviews per month`,
    },
    planSteps: [
      'Create your account',
      'Complete payment in Stripe',
      'Run your first check from the dashboard',
    ],
  },
  postLogin: {
    signingIn: 'Signing you in',
    preparing: 'Preparing your account',
    continueCta: 'Continue to dashboard',
  },
  error: {
    title: 'Could not load this page',
    body: 'Something went wrong. Try again or return to the homepage.',
    retryCta: 'Try again',
    homeCta: 'Home',
  },
  oauth: {
    continueWithGoogle: 'Continue with Google',
    continueWithGitHub: 'Continue with GitHub',
    signInFailed: 'Sign in failed. Try again.',
    separator: 'or use email',
    popupBlocked: 'Your browser blocked the sign-in popup. Allow popups, then try again.',
    discoveryError: 'Social sign-in options could not load.',
    discoveryRetry: 'Try again',
  },
  password: {
    showLabel: 'Show password',
    hideLabel: 'Hide password',
    minLength: (n: number) => `At least ${n} characters`,
  },
  signOut: {
    cta: 'Sign out',
  },
  settings: {
    pageTitle: 'Settings',
    pageDescription: 'Manage your account and security.',
    gscConnectedTitle: 'Google Search Console connected',
    gscNotConnectedTitle: 'Google Search Console was not connected',
    gscRetry: 'Try connecting again.',
    gscErrors: {
      gsc_not_configured: 'Google Search Console is not configured on this deployment.',
      gsc_connect_failed: 'Google Search Console could not be connected. Try again.',
      gsc_denied: 'Google Search Console access was not granted.',
      gsc_invalid_state: 'That Google Search Console connection link expired. Try again.',
      gsc_no_sites: 'No verified Google Search Console properties were available for this account.',
    } as Record<string, string>,
    gsc: {
      title: 'Google Search Console',
      connectBody:
        'Connect to see search performance, indexing status, and keyword data in your reports',
      connectedTo: (site: string) => `Connected to ${site}`,
      connectedFallback: 'your property',
      connectedBadge: 'Connected',
      connectCta: 'Connect',
      disconnectCta: 'Disconnect',
      disconnectTitle: 'Disconnect Search Console',
      disconnectDescription:
        'Your reports will no longer include search performance data. This will not delete past data.',
      disconnectConfirm: 'Disconnect',
    },
    account: {
      title: 'Account',
      description: 'Your plan, name, email, and password.',
      planLabel: 'Plan',
      upgradeCta: 'Upgrade',
      managePlanCta: 'Manage plan',
      nameLabel: 'Name',
      saveCta: 'Save changes',
      saving: 'Saving\u2026',
      saveSuccess: 'Changes saved',
      emailLabel: 'Email address',
      verified: 'Verified',
      notVerified: 'Not verified',
      changeEmailSuccess: 'Check your new email to confirm the change',
      verifyCta: 'Send verification',
      verifySending: 'Sending\u2026',
      verifySuccess: 'Verification email sent',
      passwordTitle: 'Password',
      currentPasswordLabel: 'Current password',
      newPasswordLabel: 'New password',
      passwordIncomplete: 'Enter your current password and a new password of at least 8 characters.',
      changePasswordSuccess: 'Password changed and other sessions revoked',
      unsavedTitle: 'Unsaved changes',
      unsavedDescription: 'Leave without saving? Your edits will be lost.',
      unsavedStay: 'Stay',
      unsavedLeave: 'Leave',
      deleteCta: 'Delete account',
      deleteDescription: 'This permanently removes your reports, screenshots, projects, and account.',
      deletePasswordLabel: 'Password, if your account has one',
      deleteConfirming: 'Sending confirmation\u2026',
      deleteConfirmTitle: 'Delete your account?',
      deleteConfirmDescription: 'This permanently deletes your account, reports, and screenshots.',
      deleteConfirmLabel: 'Delete account',
      deleteCancel: 'Cancel',
      deleteSuccess: 'Check your email to confirm account deletion',
      errorTitle: 'Could not update account',
      errorFallback: 'The account update failed',
    },
  },
  valueProps: [
    { icon: 'history' as const, text: 'Report history saved to your account' },
    { icon: 'reports' as const, text: 'Re-open reports and copy fix prompts anytime' },
    { icon: 'recheck' as const, text: 'Run update reviews after fixes to see what changed' },
  ],
  passkeyErrors: {
    cancelled: 'Passkey sign-in was cancelled or failed. Try another method.',
    notFound: 'No passkey found for this account. Try another sign-in method.',
    twoFactorNotFound: 'No passkey found. Try another device or use a backup code.',
    twoFactorCancelled: 'Passkey verification was cancelled or failed. Use a backup code.',
  },
  me: {
    loadError: 'Could not load your account.',
    claimError: 'Could not save your report to this account.',
    claimSuccess: (n: number) => `Saved ${n} report${n !== 1 ? 's' : ''} to your account`,
    claimFailure: 'Could not save your review to this account. Refresh and try again.',
  },
  passkeyEnroll: {
    title: 'Sign in faster next time',
    body: 'Use your fingerprint, face, or device PIN instead of entering a password.',
    cta: 'Create a passkey',
    skip: 'Maybe later',
    success: 'Passkey created. You can now sign in faster.',
    createError: 'Could not create passkey',
    createFailed: 'Passkey creation was cancelled or failed',
  },
  connectedAccounts: {
    title: 'Sign-in methods',
    description: 'How you sign in, including passkeys and two-factor authentication.',
    google: 'Google',
    github: 'GitHub',
    password: 'Password',
    passkeys: 'Passkeys',
    connected: 'Connected',
    notConnected: 'Not connected',
    noPassword: 'Not set',
    signedInVia: (method: string) => `Signed in via ${method}`,
  },
  privacyNote: 'By creating an account, you agree to our Privacy Policy and Terms of Service.',
  forgotPassword: {
    title: 'Reset your password',
    subtitle: 'Enter your email and we\u2019ll send a reset link',
    sentSubtitle: 'Check your inbox',
    sentBody: 'If an account exists for that email, we sent a password reset link.',
    cta: 'Send reset link',
    backToSignIn: 'Back to sign in',
    error: 'Could not send reset email. Try again.',
    notConfigured: 'Password reset requires email to be configured on the server.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
  },
  resetPassword: {
    title: 'Choose a new password',
    subtitle: 'Must be at least 8 characters',
    cta: 'Update password',
    mismatch: 'Passwords do not match',
    success: 'Password updated. Sign in with your new password.',
    error: 'Could not reset password. The link may have expired.',
    invalidTitle: 'Invalid reset link',
    invalidSubtitle: 'This link expired or was already used',
    invalidBody: 'Request a new password reset link to continue.',
    requestNewLink: 'Request a new link',
    newPasswordLabel: 'New password',
    confirmPasswordLabel: 'Confirm password',
  },
} as const

export const SHARE_COPY = {
  access: {
    openingTitle: 'Opening shared report',
    openingBody: 'Checking that this link is still available.',
    retry: 'Try again',
    openFailed: 'Could not open this share link.',
    passwordTitle: 'Password required',
    passwordBody: 'This report is protected. Enter its password to continue.',
    passwordLabel: 'Share password',
    passwordPlaceholder: 'Enter password',
    checking: 'Checking…',
    viewReport: 'View report',
  },
} as const

export const LOCKED_INSPECTION = {
  headline: 'Sign in to inspect this Flag',
  body: 'This report includes evidence, screenshots, and fix prompts for every flag.',
  features: [
    'Screenshot evidence with interactive pins',
    'Detailed explanation of the Flag',
    'Why this matters for your users',
    'How to verify the fix',
    'Fix prompt for your editor',
  ],
  primaryCta: 'Sign in',
  secondaryCta: 'Create free account',
} as const

export const LOCKED_CONTENT_TEASER = {
  defaultLabel: 'Sign up to view',
  fixPromptLabel: 'Create a free account to get the fix prompt for this flag',
  primaryCta: 'Create free account',
  secondaryCta: 'Sign in',
} as const

export const SAMPLE_FIX = {
  label: 'Example fix',
  fixTitle: 'Fix',
  signInCta: 'Sign in',
  subtext: (n: number) => `One sample fix below. Create a free account to see all ${n} fix prompts, save reports, run update reviews, and get more product reviews each month.`,
  primaryCta: 'Create free account',
} as const

export const SCAN_LIMIT_GATE = {
  signup: {
    title: 'Create a free account to continue',
    body: `You have already used your anonymous product review. Create a free account for fix prompts, saved reports, and ${PRICING_COPY.freeProductReviewsPerMonth} product reviews per month.`,
    primaryCta: 'Create free account',
    secondaryCta: 'Sign in',
    exit: 'Leave this page',
  },
  upgrade: {
    title: 'Product review limit reached',
    body: `You have used all the product reviews in your current monthly allowance. Upgrade to Pro for ${PRICING_COPY.proProductReviewsPerMonth} product reviews per month, or wait for renewal.`,
    primaryCta: 'Upgrade to Pro',
    secondaryCta: 'See plans',
    exit: 'Leave this page',
  },
} as const

export const REPORT_UPGRADE_GATE = {
  title: 'Upgrade to continue reviewing',
  body: 'You have used all the product reviews in your current plan. Upgrade for more product reviews each month.',
  primaryCta: 'Upgrade to Pro',
  saving: 'Preparing your upgrade',
  savingBody: 'Taking you to checkout.',
} as const
