import { CARD_CATALOG } from '@/lib/sites/card-areas'

/** Homepage examples are illustrative. Evidence images come from deterministic local fixtures. */
const EXAMPLE_HOST = 'everydaygoods.example'

export type HomepageAudienceKey = 'website' | 'store' | 'webapp'

export const CARE_HOME = {
  brand: 'FixFlags', signIn: 'Sign in',
  headlineLines: ['Your software runs.', 'FixFlags watches.'],
  hero: {
    body: 'Know when your site is down, checkout breaks, or signup stops working. FixFlags raises a Flag with what failed.',
    proof: '100+ automated tests. Real browser journeys. Independent verification.',
    trust: 'No credit card required',
    cta: 'Analyze',
    placeholder: 'yourwebsite.com',
  },
  boardHost: EXAMPLE_HOST,
  boardLabel: 'Sample Site',
  boardSummary: '4 Flags. View flags.',
  exampleCheckedAt: '2026-09-14T09:00:00.000Z',
  boardAria: `${EXAMPLE_HOST} board`,
  details: { flagsLabel: 'Flags in this category' },
  site: {
    label: CARD_CATALOG.site.name,
    status: '1 Flag',
    answer: 'Pricing page is unavailable',
    imageAlt: 'Everyday Goods store with a Canvas Tote product page',
    question: CARD_CATALOG.site.question,
    facts: ['Page: /pricing', 'Observed: 404 Not Found', '11 other public pages remained reachable'],
    coverage: 'The sample Site names the unavailable page and the public pages included in the latest analysis.',
  },
  flag: {
    name: CARD_CATALOG.conversion.name,
    status: '2 Flags',
    title: 'Add to cart stopped working',
    body: 'The cart stayed empty after Add to cart.',
    outcome: 'Complete a purchase',
    action: 'See the Flag',
    cropAlt: 'Canvas Tote product page where Add to cart leaves the cart empty',
    facts: [
      'Page: /products/canvas-tote',
      'Action: select Add to cart',
      'Observed: the button responds but the cart remains empty',
    ],
    question: CARD_CATALOG.conversion.question,
  },
  cards: [
    { id: 'security', name: CARD_CATALOG.security.name, value: 'HTTPS protections checked', detail: 'HTTPS and key protections are in place', status: 'Clear', tone: 'good', chart: 'none',
      question: CARD_CATALOG.security.question, answer: 'Protected',
      facts: ['HTTPS is on', 'The certificate is valid', 'No mixed content'],
      coverage: 'HTTPS, certificate, and mixed-content checks on the pages explored.' },
    { id: 'search', name: CARD_CATALOG.search.name, value: '12 pages can be crawled', detail: 'Checked pages can be found and crawled', status: 'Clear', tone: 'good', chart: 'none',
      question: CARD_CATALOG.search.question, answer: '12 pages can be crawled',
      facts: ['Checked pages allow search-engine access', 'This is crawlability, not a ranking claim'],
      coverage: 'Crawlability only. Rankings require separate search-performance data.' },
    { id: 'performance', name: CARD_CATALOG.performance.name, value: '3.1s', detail: 'Main content is slow on the campaign page', status: '1 Flag', tone: 'attention', chart: 'none',
      question: CARD_CATALOG.performance.question, answer: '3.1s for main content',
      facts: ['Largest Contentful Paint on the homepage', 'People may wait before they can use the page'],
      coverage: 'A live result identifies the page, device, and capture conditions.' },
    { id: 'tracking', name: CARD_CATALOG.tracking.name, value: 'Tracking observed', detail: 'Public events appeared in the browser', status: 'Clear', tone: 'good', chart: 'bars',
      question: CARD_CATALOG.tracking.question, answer: 'Public events were observed',
      facts: ['Expected public events were observed', 'A missing expected event can become a Flag'],
      coverage: 'A live card names the events and observation window.' },
  ],
  library: {
    uptime: {
      id: 'uptime', name: CARD_CATALOG.uptime.name, value: 'Reachable',
      detail: 'The website responded each time we checked', status: 'Clear',
      question: CARD_CATALOG.uptime.question, answer: 'Reachable',
      facts: ['Checked from the public internet', 'No downtime in the observed window'],
      coverage: 'A live card names the observation window and last success.',
    },
    accessibility: {
      id: 'accessibility', name: CARD_CATALOG.accessibility.name, value: 'Essentials checked',
      detail: 'Labels, keyboard access, and contrast on opened pages', status: 'Clear',
      question: CARD_CATALOG.accessibility.question, answer: 'Essentials checked',
      facts: ['Automated checks on public pages', 'Does not replace a human review'],
      coverage: 'Automated accessibility coverage is limited to what the browser can observe.',
    },
  },
  conversionFlags: [
    { id: 'checkout-flag', title: 'Add to cart stopped working', href: '#flag-example' },
    { id: 'signup-flag', title: 'Signup no longer completes', href: '#monitoring' },
  ],
  performanceFlags: [{ id: 'perf-1', title: 'Campaign page is slow', href: '#product' }],
  monitoring: {
    label: 'Continuous monitoring',
    title: 'Know when your site stops working.',
    body: 'FixFlags checks the live site and raises a Flag when a page or customer journey fails.',
    notifications: [
      { status: 'Flag', title: 'Website is down', detail: '503 on /', time: 'Just now', tone: 'bad' },
      { status: 'Flag', title: 'Checkout stopped working', detail: 'Canvas Tote · Cart stayed empty', time: '4 min ago', tone: 'bad' },
      { status: 'Flag · When configured', title: 'Signup stopped working', detail: '/signup · No confirmation', time: '7 min ago', tone: 'bad' },
      { status: 'Verified', title: 'Checkout works again', detail: 'Fresh browser journey passed', time: '12 min ago', tone: 'good' },
    ],
  },
  workflow: {
    label: 'Flag. Fix. Verify.',
    title: 'A green deploy does not mean the live site works.',
    body: 'FixFlags reruns the same live journey before a Flag closes.',
    steps: [
      { id: 'flag', label: 'Flag', title: 'Checkout stopped working.', body: 'Product page → Add to cart → cart stayed empty.' },
      { id: 'fix', label: 'Fix', title: 'Fix the right thing.', body: 'Page, steps, observed result, expected result.' },
      { id: 'verify', label: 'Verify', title: 'Know it works again.', body: 'The same live journey passed in a fresh browser.' },
    ],
    failedAlt: 'Canvas Tote product page after Add to cart with an empty cart',
    passedAlt: 'Canvas Tote product page with one item in the cart and a checkout button',
    passedLink: 'Open the verified checkout capture',
    failedLabel: '1 Flag',
    failedTitle: 'Cart stayed empty',
    viewFlag: 'View flag',
    compareLabel: 'Drag to compare the empty cart with the verified cart',
    passedLabel: 'Verified',
    passedTitle: 'Cart updated. Checkout opened.',
    proofLabel: 'Live checkout journey',
    page: '/products/canvas-tote',
    source: 'Browser journey · Product to checkout',
    instructions: 'On the Canvas Tote page, select Add to cart and observe that the cart remains empty. Restore the add-to-cart action so the selected product appears in the cart and checkout remains reachable. Publish the change, then run a fresh browser journey and verify that the cart shows one item and checkout opens.',
  },
  coverage: {
    label: 'What FixFlags watches',
    title: 'Watch what people came to do.',
    body: 'Choose the outcome. FixFlags keeps checking it on the live site.',
    analysisLabel: 'Also analyzed',
    analysis: ['Performance', 'Accessibility', 'Search', 'Security', 'Tracking', 'Layout'],
    boundary: 'Signup needs synthetic test data plus an exact-origin reset and cleanup path you control. FixFlags authorizes it only after a successful dry run. Login and password reset are not supported yet.',
    audiences: [
      {
        id: 'website', label: 'Website', question: 'Is the site reachable?', monitored: 'Public page availability',
      },
      {
        id: 'store', label: 'Store', question: 'Can customers buy?', monitored: 'Product → cart → checkout',
      },
      {
        id: 'webapp', label: 'Web app', question: 'Can people sign up?', monitored: 'Configured signup → confirmation',
      },
    ] satisfies ReadonlyArray<{ id: HomepageAudienceKey; label: string; question: string; monitored: string }>,
  },
  actions: {
    label: 'Flag handoff',
    title: 'Ready for the person fixing it.',
    body: 'See what happened, where it happened, and what should happen instead.',
    packet: [
      { label: 'Journey', value: 'Complete a purchase' },
      { label: 'Observed', value: 'Add to cart left the cart empty' },
      { label: 'Expected', value: 'The product appears and checkout opens' },
    ],
    choices: [
      { id: 'read', title: 'Open the details', body: 'Inspect the evidence, affected page, and reproduction steps.', action: 'Open details' },
      { id: 'share', title: 'Share the Flag', body: 'Pass the same evidence and expected result to a teammate.', action: 'Copy Flag' },
      { id: 'ai', title: 'Send it to your AI', body: 'Copy an evidence-backed prompt with clear verification criteria.', action: 'Copy AI prompt' },
    ],
    copied: 'Flag copied', copyFailed: 'Copy was unavailable. Open the Flag to use the details.',
    hide: 'Hide details', verify: 'Verified only after a fresh browser journey completes the same purchase path.',
  },
  integrations: {
    label: 'Integrations',
    title: 'More context. Better Flags.',
    body: 'Start with a URL. Connect tools when you want more context around a Flag.',
    add: 'Add integration',
    addTitle: 'Add an integration',
    addBody: 'Connections add context beside a Flag. They do not mark an Outcome Clear.',
    sampleNote: 'Sample board. You connect these on your Site.',
    addAction: 'Add',
    added: 'Added',
    action: 'See how each one connects',
  },
  close: { title: 'Keep building. FixFlags keeps watch.', body: 'Start with your URL. See what works now, then keep it under watch.', pricing: 'View pricing' },
} as const
