import { CARD_CATALOG } from '@/lib/sites/card-areas'

/** Homepage examples are illustrative. Evidence images come from controlled local fixtures. */
const EXAMPLE_HOST = 'everydaygoods.example'

export const CARE_HOME = {
  brand: 'FixFlags', signIn: 'Sign in',
  headlineLines: ['Your website,', 'looked after.'],
  hero: {
    body: 'Keep building. FixFlags checks your live website across 100+ checks and real browser journeys. When something breaks, you know what happened and how to fix it.',
    trust: 'No account required · Start with a public website',
    cta: 'Check my website', placeholder: 'yourwebsite.com',
  },
  boardHost: EXAMPLE_HOST,
  boardAria: `${EXAMPLE_HOST} board`,
  previewNote: 'Controlled example, not a live assessment.',
  boardMeta: 'Checked just now',
  site: {
    label: CARD_CATALOG.site.name,
    status: 'Pages are loading',
    answer: 'Pages are loading',
    pages: '12 pages',
    flags: '1 Flag',
    imageAlt: 'Controlled Everyday goods homepage with shopping and support actions',
    question: CARD_CATALOG.site.question,
    facts: ['12 pages in this example', '1 open Conversion Flag', 'Checked just now'],
    coverage: 'Controlled example. A live Site uses the latest real capture, never a stock image.',
  },
  flag: {
    name: CARD_CATALOG.conversion.name, status: 'Needs a fix', title: 'No confirmation after contact',
    body: 'The form sends. Visitors never see that it worked.',
    outcome: 'Get in touch', action: 'See what happened',
    cropAlt: 'Controlled contact form after submit with no confirmation',
    question: CARD_CATALOG.conversion.question,
  },
  cards: [
    { id: 'security', name: CARD_CATALOG.security.name, value: 'Protected', detail: 'HTTPS and key protections are in place', status: 'Checks passed', tone: 'good', chart: 'none',
      question: CARD_CATALOG.security.question, answer: 'Protected',
      facts: ['HTTPS is on', 'The certificate is valid', 'No mixed content'],
      coverage: 'Public configuration checks in this illustrative example.' },
    { id: 'search', name: CARD_CATALOG.search.name, value: '12 pages', detail: 'Checked pages can be found and crawled', status: 'Ready to be found', tone: 'good', chart: 'none',
      question: CARD_CATALOG.search.question, answer: '12 pages can be crawled',
      facts: ['Checked pages allow search-engine access', 'This is crawlability, not a ranking claim'],
      coverage: 'Controlled crawlability example, not a ranking claim.' },
    { id: 'performance', name: CARD_CATALOG.performance.name, value: '3.1s', detail: 'Main content takes time to appear', status: 'Needs attention', tone: 'attention', chart: 'none',
      question: CARD_CATALOG.performance.question, answer: '3.1s for main content',
      facts: ['Largest Contentful Paint in this example', 'People may wait before they can use the page', 'Needs attention'],
      coverage: 'Illustrative page-load measurement. Real results identify the page, device and capture conditions.' },
    { id: 'tracking', name: CARD_CATALOG.tracking.name, value: 'Connected', detail: 'Key website events are arriving', status: 'Latest check passed', tone: 'good', chart: 'bars',
      question: CARD_CATALOG.tracking.question, answer: 'Key events are arriving',
      facts: ['Expected public events were observed', 'Investigate if an expected event disappears after a change'],
      coverage: 'Controlled tracking example. A real card names the events and observation window.' },
  ],
  workflow: {
    label: 'How FixFlags works', title: 'See the problem. Fix it. Know it works.',
    body: 'FixFlags does the checking, keeps the evidence together, and returns to the live website after the change.',
    steps: [
      { id: 'check', label: 'Check', title: 'FixFlags uses the live website.', body: 'It opens pages, follows important actions, and records what actually happens.' },
      { id: 'flag', label: 'Flag', title: 'One important action fails.', body: 'The contact form submits, but visitors never see a confirmation.' },
      { id: 'fix', label: 'Fix', title: 'The next step comes with context.', body: 'Read it, share it, or give the evidence to the AI tool you already use.' },
      { id: 'verify', label: 'Verify', title: 'A fresh check proves the result.', body: 'FixFlags repeats the same action on the live website and confirms the success state appears.' },
    ],
    failedAlt: 'Controlled contact form after submission with no confirmation message',
    passedAlt: 'Controlled contact form after submission with a clear message received confirmation',
    failedLink: 'Open failed-state capture',
    passedLink: 'Open passing-state capture',
    failedLabel: 'Needs attention',
    failedTitle: 'No confirmation appeared',
    passedLabel: 'Fresh check passed',
    passedTitle: 'Message received',
    source: 'Captured from a controlled contact-form fixture.',
    instructions: 'On the Contact page, submit the form and observe that no success message appears. Add a clear confirmation after the request succeeds. Publish the change, then run a fresh browser check and confirm that “Message received” is visible after submission.',
  },
  checks: {
    label: '100+ checks and browser journeys', title: 'Always know how your website is doing.',
    body: 'FixFlags chooses the checks that fit your website, then brings the useful answers into one place.',
    groups: [
      { id: 'pages', title: 'Pages and access', items: ['Availability', 'Broken pages and links', 'Search and crawlability', 'Structured data', 'Security'] },
      { id: 'actions', title: 'Visitor actions', items: ['Forms and interactions', 'Signups and journeys', 'Commerce behavior', 'Mobile behavior'] },
      { id: 'quality', title: 'Quality and inclusion', items: ['Performance', 'Accessibility', 'Message clarity', 'Visual stability'] },
      { id: 'signals', title: 'Signals and change', items: ['Tracking and analytics', 'Deployments and changes', 'Real visitor failures', 'Paid traffic exposure'] },
    ],
    note: 'What runs depends on what FixFlags learns your website needs to do.',
  },
  outcomes: {
    label: 'Built around your business', title: 'Tell FixFlags what your website needs to do.',
    body: 'Sell a product. Book a call. Collect a lead. Accept a donation. Run a tool. FixFlags follows the pages and actions behind the result.',
    options: [
      { id: 'sell', label: 'Sell', path: ['Product', 'Add to cart', 'Checkout'], result: 'Customers can buy' },
      { id: 'book', label: 'Book', path: ['Service', 'Choose a time', 'Confirmation'], result: 'Visitors can book' },
      { id: 'lead', label: 'Collect a lead', path: ['Landing page', 'Contact form', 'Message received'], result: 'Leads can get through' },
      { id: 'donate', label: 'Donate', path: ['Campaign', 'Donation form', 'Confirmation'], result: 'Supporters can donate' },
      { id: 'tool', label: 'Run a tool', path: ['Open tool', 'Complete action', 'See result'], result: 'The tool does its job' },
    ],
  },
  actions: {
    label: 'From attention to action', title: 'Fix it your way.',
    body: 'The evidence stays the same. Choose the way you want to move the work forward.',
    choices: [
      { id: 'read', title: 'Read it', body: 'See what failed, why it matters, and the recommended change.', action: 'Read the fix' },
      { id: 'share', title: 'Share it', body: 'Give a teammate the evidence, reproduction steps, and expected result.', action: 'Copy for a teammate' },
      { id: 'ai', title: 'Work with your AI', body: 'Copy one prompt with the Flag, evidence, expected result, and how to verify.', action: 'Copy prompt' },
    ],
    copied: 'Fix copied', copyFailed: 'Copy was unavailable. Read the fix below.',
    hide: 'Hide the fix', verify: 'Every route ends with a fresh FixFlags check.',
  },
  mcp: {
    label: 'Work with your AI', title: 'No more explaining the problem twice.',
    body: 'Copy the active Flag, evidence, reproduction steps, expected result, and verification criteria into the AI tool you already use.',
    flow: [
      { title: 'FixFlags finds and explains', body: 'A current Flag with evidence, not a vague request.' },
      { title: 'Your AI edits with context', body: 'It works in your codebase with the information FixFlags collected.' },
      { title: 'FixFlags checks the live result', body: 'A fresh browser check confirms whether the action works.' },
    ],
    copy: 'Copy prompt',
    aiLabel: 'Your AI',
    note: 'You approve the work. FixFlags does not edit your repository by itself.',
  },
  quiet: {
    title: 'You keep building. FixFlags keeps watch.',
    body: 'When an important page or action breaks, you know what happened and have a clear way to fix it.',
    exampleNote: 'Example of watch, not a live feed.',
    notifications: [
      { status: 'Recovered', title: 'Checkout is working again', detail: 'Buy · Fresh browser check passed', time: '12 min ago', tone: 'good' },
      { status: 'Slower than usual', title: 'The pricing page now takes 4.2s', detail: 'Performance · Mobile', time: '4 min ago', tone: 'warn' },
      { status: 'Needs attention', title: 'Contact form stopped confirming messages', detail: 'Get in touch · Evidence and fix inside', time: 'Just now', tone: 'bad' },
    ],
  },
  shopify: { title: 'Running Shopify?', body: 'Explore the Shopify connection for the same website and its purchase journeys.', cta: 'Connect Shopify' },
  close: { title: 'Know how your website is doing.', body: 'Start with your URL. FixFlags will show you what needs attention and what to do next.', pricing: 'View pricing' },
} as const
