import { CARD_CATALOG } from '@/lib/sites/card-areas'

/** Homepage examples are illustrative. Evidence images come from deterministic local fixtures. */
const EXAMPLE_HOST = 'everydaygoods.example'

export type HomepageAudienceKey = 'website' | 'store' | 'webapp'

export const CARE_HOME = {
  brand: 'FixFlags', signIn: 'Sign in',
  headlineLines: ['Your software runs.', 'FixFlags watches.'],
  hero: {
    body: 'FixFlags checks your live website, shows what needs attention, and lets you verify your fixes with fresh evidence.',
    proof: '100+ automated tests. Real browser journeys. Independent verification.',
    trust: 'No credit card required',
    cta: 'Analyze',
    placeholder: 'yourwebsite.com',
  },
  boardHost: EXAMPLE_HOST,
  boardLabel: 'Sample Site',
  boardSummary: '2 Flags · Analysis incomplete',
  exampleCheckedAt: '2026-09-14T09:00:00.000Z',
  boardAria: `${EXAMPLE_HOST} board`,
  details: { flagsLabel: 'Flags in this category' },
  site: {
    label: CARD_CATALOG.site.name,
    status: '1 Flag',
    answer: 'Pricing page is unavailable',
    imageAlt: 'Everyday Goods store with a Canvas Tote product page',
    question: CARD_CATALOG.site.question,
    facts: ['Page: /pricing', 'Observed: 404 Not Found', '11 other public pages remained reachable'],
    coverage: 'The sample Site names the unavailable page and the public pages included in the latest analysis.',
  },
  flag: {
    name: CARD_CATALOG.conversion.name,
    status: '1 Flag',
    title: 'Add to cart stopped working',
    body: 'The cart stayed empty after Add to cart.',
    outcome: 'Complete a purchase',
    action: 'See the Flag',
    cropAlt: 'Canvas Tote product page where Add to cart leaves the cart empty',
    facts: [
      'Page: /products/canvas-tote',
      'Action: select Add to cart',
      'Observed: the button responds but the cart remains empty',
    ],
    question: CARD_CATALOG.conversion.question,
  },
  cards: [
    { id: 'security', name: CARD_CATALOG.security.name, value: 'HTTPS protections checked', detail: 'HTTPS and key protections are in place', status: 'Clear', tone: 'good', chart: 'none',
      question: CARD_CATALOG.security.question, answer: 'Protected',
      facts: ['HTTPS is on', 'The certificate is valid', 'No mixed content'],
      coverage: 'HTTPS, certificate, and mixed-content checks on the pages explored.' },
    { id: 'search', name: CARD_CATALOG.search.name, value: '12 pages can be crawled', detail: 'Checked pages can be found and crawled', status: 'Clear', tone: 'good', chart: 'none',
      question: CARD_CATALOG.search.question, answer: '12 pages can be crawled',
      facts: ['Checked pages allow search-engine access', 'This is crawlability, not a ranking claim'],
      coverage: 'Crawlability only. Rankings require separate search-performance data.' },
    { id: 'performance', name: CARD_CATALOG.performance.name, value: '3.1s', detail: 'Main content is slow on the campaign page', status: '1 Flag', tone: 'attention', chart: 'none',
      question: CARD_CATALOG.performance.question, answer: '3.1s for main content',
      facts: ['Largest Contentful Paint on the homepage', 'People may wait before they can use the page'],
      coverage: 'A live result identifies the page, device, and capture conditions.' },
    { id: 'tracking', name: CARD_CATALOG.tracking.name, value: 'Tracking observed', detail: 'Public events appeared in the browser', status: 'Clear', tone: 'good', chart: 'bars',
      question: CARD_CATALOG.tracking.question, answer: 'Public events were observed',
      facts: ['Expected public events were observed', 'A missing expected event can become a Flag'],
      coverage: 'A live card names the events and observation window.' },
  ],
  library: {
    uptime: {
      id: 'uptime', name: CARD_CATALOG.uptime.name, value: 'Reachable',
      detail: 'The website responded each time we checked', status: 'Clear',
      question: CARD_CATALOG.uptime.question, answer: 'Reachable',
      facts: ['Checked from the public internet', 'No downtime in the observed window'],
      coverage: 'A live card names the observation window and last success.',
    },
    accessibility: {
      id: 'accessibility', name: CARD_CATALOG.accessibility.name, value: 'Essentials checked',
      detail: 'Labels, keyboard access, and contrast on opened pages', status: 'Clear',
      question: CARD_CATALOG.accessibility.question, answer: 'Essentials checked',
      facts: ['Automated checks on public pages', 'Does not replace a human review'],
      coverage: 'Automated accessibility coverage is limited to what the browser can observe.',
    },
  },
  conversionFlags: [
    { id: 'checkout-flag', title: 'Add to cart stopped working', href: '#flag-example' },
  ],
  performanceFlags: [{ id: 'perf-1', title: 'Campaign page is slow', href: '#product' }],
  monitoring: {
    label: 'Monitoring',
    summary: 'Pricing page and checkout · Daily checks',
    action: 'See what’s watched',
    detailTitle: 'What FixFlags keeps checking',
    sample: 'Sample monitoring · 14 Sep 2026',
    cadence: 'Daily checks', next: 'Next check', nextValue: '15 Sep · 09:00 UTC', last: 'Last checked',
    rows: [
      { name: 'Does the pricing page open?', scope: '/pricing · public page availability', status: '1 Flag', state: 'problem', last: '14 Sep · 09:00 UTC' },
      { name: 'Can customers reach checkout?', scope: 'Product → cart → checkout. No payment or order.', status: '1 Flag', state: 'problem', last: '14 Sep · 09:00 UTC' },
    ],
    unconfiguredTitle: 'Signup is not being watched',
    unconfiguredBody: 'Signup needs a safe test account, a reset and cleanup process, and your authorization before checks can begin.',
    notScheduled: 'Not scheduled',
    note: 'Scheduled checks can find problems at the next check, not the moment they happen. The other analysis areas have their own scope and check times.',
    setup: 'Monitoring starts after you choose your checks and turn it on. This sample schedule does not run from this page; your available schedule depends on your plan.',
  },
  workflow: {
    label: 'Flag. Fix. Verify.',
    title: 'See the problem. Know when it’s fixed.',
    body: 'Give the evidence to your teammate or AI. After the fix, let FixFlags check again.',
    steps: [
      { id: 'flag', label: 'Flag', title: 'The cart stayed empty.', body: 'Add to cart responded, but the product never appeared.' },
      { id: 'fix', label: 'Fix', title: 'Know what to fix.', body: 'Share what happened, where, and what should happen instead.' },
      { id: 'verify', label: 'Verify', title: 'Check the fix.', body: 'FixFlags checks again. Recovery needs fresh evidence that the same action works.' },
    ],
    failedAlt: 'Canvas Tote product page after Add to cart with an empty cart',
    passedAlt: 'Canvas Tote product page with one item in the cart and a Checkout control',
    passedLink: 'Open the recovery example',
    failedLabel: '1 Flag',
    failedTitle: 'Cart stayed empty',
    viewFlag: 'View flag',
    compareLabel: 'Compare the empty cart with the recovery example',
    passedLabel: 'Sample recovery',
    passedTitle: 'The product is in the cart',
    proofLabel: 'Sample cart problem',
    page: '/products/canvas-tote',
    source: 'Local browser fixtures · Product and cart',
    instructions: 'On the Canvas Tote page, select Add to cart and observe that the cart remains empty. Restore the add-to-cart action so the selected product appears in the cart and checkout remains reachable. Publish the change, then run a fresh browser journey and verify that the cart shows one item and checkout opens.',
  },
  coverage: {
    label: 'What FixFlags watches',
    title: 'Watch what people came to do.',
    body: 'Choose the outcome. FixFlags keeps checking it on the live site.',
    analysisLabel: 'Also analyzed',
    analysis: ['Performance', 'Accessibility', 'Search', 'Security', 'Tracking', 'Layout'],
    boundary: 'Signup needs synthetic test data plus an exact-origin reset and cleanup path you control. FixFlags authorizes it only after a successful dry run. Login and password reset are not supported yet.',
    audiences: [
      {
        id: 'website', label: 'Website', question: 'Is the site reachable?', monitored: 'Public page availability',
      },
      {
        id: 'store', label: 'Store', question: 'Can customers buy?', monitored: 'Product → cart → checkout',
      },
      {
        id: 'webapp', label: 'Web app', question: 'Can people sign up?', monitored: 'Configured signup → confirmation',
      },
    ] satisfies ReadonlyArray<{ id: HomepageAudienceKey; label: string; question: string; monitored: string }>,
  },
  actions: {
    label: 'Flag handoff',
    title: 'Ready for the person fixing it.',
    body: 'See what happened, where it happened, and what should happen instead.',
    packet: [
      { label: 'Journey', value: 'Complete a purchase' },
      { label: 'Observed', value: 'Add to cart left the cart empty' },
      { label: 'Expected', value: 'The product appears and checkout opens' },
    ],
    choices: [
      { id: 'read', title: 'Open the details', body: 'Inspect the evidence, affected page, and reproduction steps.', action: 'Open details' },
      { id: 'share', title: 'Share the Flag', body: 'Pass the same evidence and expected result to a teammate.', action: 'Copy Flag' },
      { id: 'ai', title: 'Send it to your AI', body: 'Copy an evidence-backed prompt with clear verification criteria.', action: 'Copy AI prompt' },
    ],
    copied: 'Flag copied', copyFailed: 'Copy was unavailable. Open the Flag to use the details.',
    hide: 'Hide details', verify: 'Verified only after a fresh browser journey completes the same purchase path.',
  },
  integrations: {
    label: 'Integrations',
    title: 'More context. Better Flags.',
    body: 'Start with a URL. Connect tools when you want more context around a Flag.',
    add: 'Add integration',
    addTitle: 'Add an integration',
    addBody: 'Connections add context beside a Flag. They do not mark an Outcome Clear.',
    sampleNote: 'Sample board. You connect these on your Site.',
    addAction: 'Add',
    added: 'Added',
    action: 'See how each one connects',
  },
  close: { title: 'Start with your website.', body: 'See what needs attention. Then choose what FixFlags keeps watching.', pricing: 'View pricing' },
} as const

/** Illustrative analysis snapshot, not a customer assessment or live schedule. */
export type SampleCategory = {
  id: import('@/lib/sites/card-areas').SiteCardArea
  name: string
  state: import('@/lib/sites/card-areas').CardHealthState
  answer: string
  context: string
  status: string
  flagCount: number
  scope: string
  checkedAt: string | null
  results: readonly { label: string; status: string; detail: string }[]
  flag?: 'availability' | 'checkout'
  connection?: { label: string; body: string; href: string }
}

export const HOMEPAGE_SAMPLE = {
  exploreAction: 'Explore the sample',
  identityAlt: 'Everyday Goods sample homepage, shown for website identity',
  title: 'Know how your website is doing.',
  note: 'Illustrative results and schedule. Images captured from local examples.',
  summary: '2 Flags need attention',
  groups: { attention: 'Needs attention', checked: 'Checked', uncertain: 'Still to check' },
  snapshot: '14 Sep 2026 · 09:00 UTC',
  snapshotLabel: 'Last analyzed',
  coverageAction: 'Coverage and check times',
  analyzeAction: 'Analyze your website',
  overviewTitle: 'Website condition',
  overviewBody: 'Two Flags need a fix. Performance is incomplete, Security is out of date, and Tracking is not configured.',
  coverageTitle: 'What this sample covers',
  coverageBody: 'Analysis and scheduled behavior have different scopes. A successful result only describes the evidence shown.',
  resultsTitle: 'Results in this area',
  sampleLabel: 'Sample',
  detailAction: 'View Flag and evidence',
  backAction: 'Back to results',
  fixTitle: 'Fix guidance',
  observedLabel: 'Observed',
  expectedLabel: 'Expected',
  scopeLabel: 'Scope',
  proofTitle: 'Recovery example',
  proofBody: 'The local recovery fixture shows one product in the cart and a Checkout control. It illustrates the expected result; this page does not run verification or establish a customer recovery.',
  availabilityTitle: 'Pricing page is unavailable',
  availabilityObserved: 'A request to /pricing received HTTP 404 in the local fixture.',
  availabilityExpected: 'The pricing page responds successfully and displays its content.',
  availabilityFix: 'Restore the /pricing route and its content, then verify that the same URL responds successfully.',
  availabilityPrompt: 'FixFlags sample Flag: /pricing returns HTTP 404. Restore the route and pricing content. After publishing, request a fresh independent check of /pricing and confirm a successful response. Copying this prompt does not resolve a Flag.',
  availabilityAlt: 'Local pricing fixture: HTTP 404, page unavailable',
  unresolved: 'Recovery has not been verified for this sample Flag.',
  guidanceCopied: 'Sample fix guidance copied. No verification was started.',
  copyFailed: 'Clipboard unavailable. Select and copy the guidance below.',
  sampleCopy: 'Copy sample fix guidance',
  connections: 'Connections add context; they do not establish recovery.',
  recoveryAction: 'View sample recovery',
  sources: { http: 'Local HTTP fixture', browser: 'Local browser fixture', diagnostics: 'Illustrative diagnostic results' },
  guidanceLabel: 'Sample fix guidance',
  availabilityScope: '/pricing · public page response',
  checkoutExpected: 'The selected product appears in the cart and checkout opens.',
  proofAlt: 'Local recovery fixture: Canvas Tote in the cart with a Checkout control',
  notVerified: 'Not verified',
  categories: [
    { id: 'site', name: CARD_CATALOG.site.name, state: 'problem', answer: 'Pricing page is unavailable', context: 'Homepage and product page opened', status: '1 Flag', flagCount: 1, flag: 'availability',
      scope: 'Homepage, product page and pricing URL. A page response does not establish a purchase journey.', checkedAt: '2026-09-14T09:00:00Z',
      results: [ { label: '/pricing', status: 'Flag', detail: 'HTTP 404 in the local availability fixture.' }, { label: 'Homepage and product page', status: 'Checked', detail: 'Public pages opened in the sample browser.' } ] },
    { id: 'conversion', name: CARD_CATALOG.conversion.name, state: 'problem', answer: 'Add to cart leaves the cart empty', context: 'Canvas Tote · product to cart', status: '1 Flag', flagCount: 1, flag: 'checkout',
      scope: 'Product → Add to cart → cart → checkout entry. No payment or real order.', checkedAt: '2026-09-14T09:00:00Z',
      results: [ { label: 'Checkout journey', status: 'Flag', detail: 'The cart stayed empty after Add to cart.' }, { label: 'Safe Signup', status: 'Not configured', detail: 'Requires synthetic data, an exact-origin reset and cleanup path, and authorization after a successful dry run.' } ],
      connection: { label: 'Shopify context', body: 'A connected store can add product context beside the same browser evidence.', href: '/shopify' } },
    { id: 'security', name: CARD_CATALOG.security.name, state: 'unknown', answer: 'Needs a fresh check', context: 'Earlier checks are out of date', status: 'Out of date', flagCount: 0,
      scope: 'Public security basics only. No server-side or penetration-test claim.', checkedAt: '2026-09-01T09:00:00Z',
      results: [ { label: 'Public protections', status: 'Out of date', detail: 'The earlier illustrative result is too old to describe the current snapshot.' }, { label: 'Server-side security', status: 'Outside coverage', detail: 'Not established by public browser inspection.' } ] },
    { id: 'search', name: CARD_CATALOG.search.name, state: 'healthy', answer: 'Search engines can access checked pages', context: 'Homepage and product page', status: '0 Flags', flagCount: 0,
      scope: 'Illustrative title and crawl-access results for the homepage and product page. No ranking claim.', checkedAt: '2026-09-14T09:00:00Z',
      results: [ { label: 'Page titles', status: 'Checked', detail: 'Both sample pages have descriptive titles.' }, { label: 'Crawl access', status: 'Checked', detail: 'The illustrative pages allow search-engine access.' }, { label: 'Search rankings', status: 'Outside coverage', detail: 'Crawlability does not establish visibility or rankings.' } ],
      connection: { label: 'Search Console context', body: 'A connection adds search-performance context alongside technical analysis.', href: '/integrations#search-console' } },
    { id: 'performance', name: CARD_CATALOG.performance.name, state: 'unknown', answer: 'No mobile speed result', context: 'Mobile measurement unavailable', status: 'Partial', flagCount: 0,
      scope: 'This illustrative snapshot has no complete mobile lab measurement. No loading-time value is asserted.', checkedAt: null,
      results: [ { label: 'Mobile lab measurement', status: 'Unavailable', detail: 'The run did not produce a usable measurement.' }, { label: 'Next step', status: 'Recommendation', detail: 'Run analysis again before drawing a performance conclusion.' } ] },
    { id: 'tracking', name: CARD_CATALOG.tracking.name, state: 'unknown', answer: 'Choose the events to check', context: 'No events selected for checking', status: 'Not configured', flagCount: 0,
      scope: 'Public instrumentation can be observed; expected event delivery requires defined scope.', checkedAt: null,
      results: [ { label: 'Expected events', status: 'Not configured', detail: 'This sample has no agreed events to verify.' }, { label: 'Next step', status: 'Recommendation', detail: 'Define the events that matter before treating a missing event as a Flag.' } ],
      connection: { label: 'Analytics context', body: 'Audience context enriches the result. Session counts do not verify a journey.', href: '/integrations#analytics' } },
    { id: 'accessibility', name: CARD_CATALOG.accessibility.name, state: 'healthy', answer: 'Controls have accessible names', context: 'Automated checks · 2 pages', status: '0 Flags', flagCount: 0,
      scope: 'Illustrative automated results on the homepage and product page. Human accessibility review remains outside this sample.', checkedAt: '2026-09-14T09:00:00Z',
      results: [ { label: 'Controls have names', status: 'Checked', detail: 'The sample reports names for the public controls it inspected.' }, { label: 'Human review', status: 'Outside coverage', detail: 'Automated checks cannot establish complete accessibility.' } ] },
  ] as readonly SampleCategory[],
} as const
