export const INTEGRATIONS_PAGE = {
  hero: {
    label: 'Integrations',
    title: 'Better with the tools you already use.',
    body: 'FixFlags checks your live website. Connect store, traffic, and search data to see more context beside each Flag. Explore what works today and what we are building next.',
  },
  currentListTitle: 'What it adds today',
  futureListTitle: 'Checks it could unlock',
  proposedLabel: 'Exploring',
  availableLabel: 'Available',
  items: [
    {
      id: 'shopify', status: 'available', title: 'Shopify', logo: '/brand/integrations/shopify.svg',
      purpose: 'Storefront and checkout',
      summary: 'Product information and an independent walk from a saleable product to checkout.',
      checks: ['Product information for connected stores', 'Cart and checkout entry on selected saleable products', 'Purchase-path Flags when a watched step fails'],
      action: 'Read integration guide', href: '/docs/integrations/shopify',
    },
    {
      id: 'analytics', status: 'available', title: 'Google Analytics', logo: '/brand/integrations/google-analytics.svg',
      purpose: 'Page traffic',
      summary: 'Sessions on the pages FixFlags watches.',
      checks: ['Sessions on watched pages over the last 28 days', 'Traffic context beside page-specific Flags', 'A matched Analytics property for your Site'],
      action: 'Read integration guide', href: '/docs/integrations/google-analytics',
    },
    {
      id: 'search-console', status: 'available', title: 'Google Search Console', logo: '/brand/integrations/google-search-console.svg',
      purpose: 'Search demand',
      summary: 'Queries, impressions, and clicks for matching Site pages.',
      checks: ['Queries and impressions for matching Site pages', 'Search clicks beside page-specific Flags', 'A matched Search Console property for your Site'],
      action: 'Read integration guide', href: '/docs/integrations/google-search-console',
    },
    {
      id: 'github', status: 'planned', title: 'GitHub', logo: '/brand/integrations/github.svg',
      purpose: 'Code and fix handoff',
      summary: 'Repository changes that could explain when a Flag appeared.',
      checks: ['Recent changes near the first appearance of a Flag', 'Fix pull requests linked to affected pages', 'Fresh verification after a change is published'],
    },
    {
      id: 'woocommerce', status: 'planned', title: 'WooCommerce', logo: '/brand/integrations/woocommerce.svg',
      purpose: 'Products and orders',
      summary: 'Store catalog and checkout context for WordPress shops.',
      checks: ['Product availability versus the public product page', 'Cart and checkout failures after plugin updates', 'Store API errors on purchase paths'],
    },
    {
      id: 'posthog', status: 'planned', title: 'PostHog', logo: '/brand/integrations/posthog.svg',
      purpose: 'Events and funnels',
      summary: 'Journey events and the steps where visitors stop.',
      checks: ['Missing events on watched journeys', 'Funnel steps with sudden drop-off', 'Event changes after a published fix'],
    },
    {
      id: 'stripe', status: 'planned', title: 'Stripe', logo: '/brand/integrations/stripe.svg',
      purpose: 'Payment outcomes',
      summary: 'Payment and Checkout events beside the browser journey.',
      checks: ['Payment failures versus checkout-entry failures', 'Checkout sessions that expire before completion', 'Payment-event changes after a release'],
    },
    {
      id: 'sentry', status: 'planned', title: 'Sentry', logo: '/brand/integrations/sentry.svg',
      purpose: 'Application errors',
      summary: 'Browser exceptions and releases around an affected page.',
      checks: ['New errors on pages with active Flags', 'Error spikes after a release', 'Repeated exceptions during a watched journey'],
    },
    {
      id: 'vercel', status: 'planned', title: 'Vercel', logo: '/brand/integrations/vercel.svg',
      purpose: 'Deployments and speed',
      summary: 'Production releases and performance context.',
      checks: ['First failed check after a production deployment', 'Failed or rolled-back deployments', 'Web Vital regressions after a release'],
    },
    {
      id: 'cloudflare', status: 'planned', title: 'Cloudflare', logo: '/brand/integrations/cloudflare.svg',
      purpose: 'Edge traffic and protection',
      summary: 'Edge errors and security challenges affecting visitors.',
      checks: ['5xx spikes on watched paths', 'WAF challenges blocking signup or checkout', 'Origin failures versus edge failures'],
    },
  ],
} as const
