import type { WatchInterval } from '@/lib/sites/watch-schedule'

/** Monitoring speaks about the customer's website; execution mechanics stay in evidence. */
export const MONITORING_COPY = {
  off: 'Monitoring is off.',
  offBody: 'Keep checking this website after you leave.',
  turnOn: 'Turn on monitoring',
  checkPage: 'Check this page',
  title: 'Keep this website under watch.',
  setupTitle: 'Turn on monitoring',
  setupBody: 'Here’s what FixFlags will keep checking. Your full website analysis stays available.',
  page: 'Public page',
  expectation: 'Check that this page opens.',
  existing: 'Also included',
  scope: 'This schedule covers the checks listed here. Other results remain from your latest analysis.',
  expand: 'Add more checks',
  protected: 'Checkout can be added when we find a safe way to test it. Signup needs your permission and a test account we can safely remove.',
  cadence: 'Check every',
  weekly: 'Week',
  daily: 'Day',
  activating: 'Turning on monitoring…',
  loading: 'Loading your monitoring options…',
  unavailable: 'We couldn’t load your monitoring options.',
  unavailableBody: 'Try again. Your results are still here.',
  retry: 'Try again',
  claimTitle: 'Save this website to turn on monitoring.',
  claimBody: 'Create an account or sign in. We’ll bring you back to these results.',
  signIn: 'Sign in',
  signInAgain: 'Sign in again to turn on monitoring.',
  signUp: 'Create an account',
  coverageFailed: 'We couldn’t set up this page check.',
  scheduleFailed: 'The page check is ready. We couldn’t finish setting up monitoring.',
  serviceUnavailable: 'We can’t turn on monitoring right now. Your page check is saved.',
  checkFailed: 'Monitoring is on, but we couldn’t start the first check.',
  queued: 'Monitoring is on. The first check is waiting to start.',
  requestedBefore: 'Monitoring is on. See your checks in the website overview.',
  checking: 'Checking this page…',
  firstPending: 'The first check hasn’t finished yet.',
  pageClear: 'This page opened when we checked.',
  pageFlag: 'This page needs attention.',
  couldNotCheck: 'We couldn’t check this page.',
  stale: 'The last result is out of date.',
  scheduleOnly: 'A schedule is saved, but no checks are ready to run.',
  needsAttention: 'Monitoring needs attention.',
  return: 'Back to your website',
  review: 'Review coverage',
  reviewTitle: 'What FixFlags is watching',
  reviewBody: 'Your selected checks, their latest result, and when they’ll run again.',
  addPage: 'Add this page to monitoring',
  resume: 'Finish setup',
  manage: 'Manage monitoring',
  next: 'Next scheduled check',
  last: 'Last checked',
  notRun: 'Not checked yet',
  notScheduled: 'Not scheduled',
  details: 'What happened',
  noEmails: 'Monitoring emails are off. You can change this in Settings.',
  emails: 'We’ll email you about new Flags.',
  criticalEmails: 'We’ll email you about critical Flags.',
  recoveryEmails: 'We’ll also tell you when a check verifies recovery.',
  readiness: 'We couldn’t turn on monitoring. Your results are saved.',
  cadenceUnavailable: 'That schedule isn’t available on your account. Choose one of the options shown.',
  scheduled: (interval: WatchInterval, everyMinutes?: number | null) => interval === 'daily' ? 'We’ll check these pages and actions every day.' : interval === 'weekly' ? 'We’ll check these pages and actions every week.' : interval === 'hourly' ? 'We’ll check these pages and actions every hour.' : `We’ll check these pages and actions every ${(everyMinutes ?? 60) / 60} hours.`,
  heading: (interval: WatchInterval, everyMinutes?: number | null) => interval === 'daily' ? 'Daily monitoring' : interval === 'weekly' ? 'Weekly monitoring' : interval === 'hourly' ? 'Hourly monitoring' : `Monitoring every ${(everyMinutes ?? 60) / 60} hours`,
} as const

export const MONITORING_SCHEDULE_COPY = {
  title: 'Monitoring',
  signIn: 'Sign in',
  lastCheck: 'Last check',
  historyBody: 'Monitoring for the journeys customers rely on.',
  description: 'Choose how often FixFlags checks your website.',
  sample: 'This is a sample schedule. Changes only affect this preview.',
  frequency: 'Check frequency',
  daily: 'Daily', hourly: 'Hourly', weekly: 'Weekly', custom: 'Custom', off: 'Off',
  every: 'Every', unit: 'Time unit', hours: 'Hours', days: 'Days', weeks: 'Weeks',
  loading: 'Loading available schedules…',
  retry: 'Try again',
  invalid: 'Choose a whole number between 1 and 365.',
  unavailable: 'This schedule is not available on your plan.',
  paused: 'Scheduled checks are paused.',
  cancel: 'Cancel', saving: 'Saving…', updateSample: 'Update sample schedule', save: 'Save schedule', edit: 'Edit schedule',
  loadFailed: 'Could not load available schedules.',
  saveFailed: 'Could not save this schedule.',
  differentSchedule: 'The saved schedule differs from your selection.',
  notScheduled: 'No next check scheduled',
  due: 'Next check due now',
  scheduled: 'Next check scheduled',
  checks: (cadence: string) => `${cadence} checks.`,
  everyInterval: (every: number, unit: string) => `Every ${every} ${unit}`,
  nextIn: (time: string) => `Next check in ${time}`,
  nextCompact: (time: string) => `Next in ${time}`,
  nextDue: 'Due now',
  noNext: 'Not scheduled',
} as const
