/** Monitoring speaks about the customer's website; execution mechanics stay in evidence. */
export const MONITORING_COPY = {
  off: 'Monitoring is off.',
  offBody: 'Keep checking this website after you leave.',
  turnOn: 'Turn on monitoring',
  title: 'Keep this website under watch.',
  setupTitle: 'Turn on monitoring',
  setupBody: 'Choose what FixFlags will keep checking. Your full website analysis stays available.',
  page: 'Public page',
  expectation: 'Check that this page opens.',
  existing: 'Also included',
  scope: 'This schedule covers the checks listed here. Other results remain from your latest analysis.',
  expand: 'Add more checks',
  protected: 'Checkout needs a safe, discovered route. Signup needs an authorized test setup.',
  cadence: 'Check every',
  weekly: 'Week',
  daily: 'Day',
  activating: 'Turning on monitoring…',
  loading: 'Loading your monitoring options…',
  unavailable: 'We couldn’t load your monitoring options.',
  unavailableBody: 'Try again. Your results are still here.',
  retry: 'Try again',
  claimTitle: 'Save this website to turn on monitoring.',
  claimBody: 'Create an account or sign in. We’ll bring you back to these results.',
  signIn: 'Sign in',
  signUp: 'Create an account',
  coverageFailed: 'We couldn’t set up this page check.',
  scheduleFailed: 'The page check is ready. We couldn’t finish setting up monitoring.',
  checkFailed: 'Your schedule is saved. We couldn’t start the first check.',
  queued: 'Your schedule is saved. The first check is queued.',
  requestedBefore: 'Your schedule is saved. The first check was already requested.',
  checking: 'Checking this page…',
  firstPending: 'The first check hasn’t finished yet.',
  pageClear: 'This page opened when we checked.',
  pageFlag: 'This page needs attention.',
  couldNotCheck: 'We couldn’t check this page.',
  stale: 'The last result is out of date.',
  scheduleOnly: 'A schedule is saved, but no checks are ready to run.',
  needsAttention: 'Monitoring needs attention.',
  return: 'Back to your website',
  review: 'Review coverage',
  resume: 'Finish setup',
  manage: 'Manage monitoring',
  next: 'Next scheduled check',
  last: 'Last checked',
  notRun: 'Not checked yet',
  notScheduled: 'Not scheduled',
  details: 'What happened',
  noEmails: 'Monitoring emails are off. You can change this in Settings.',
  emails: 'We’ll email you about new Flags.',
  criticalEmails: 'We’ll email you about critical Flags.',
  recoveryEmails: 'We’ll also tell you when a check verifies recovery.',
  readiness: 'We couldn’t turn on monitoring. Your results are saved.',
  cadenceUnavailable: 'That schedule isn’t available on your account. Choose one of the options shown.',
  scheduled: (interval: 'weekly' | 'daily') => interval === 'daily' ? 'We’ll check these pages and actions every day.' : 'We’ll check these pages and actions every week.',
  heading: (interval: 'weekly' | 'daily') => interval === 'daily' ? 'Daily monitoring' : 'Weekly monitoring',
} as const
